### PR TITLE
Fix #3648: `Serialization.unmarshal` fails to deserialize YAML with single document in presence of document delimiter(`---`)

### LINKED ISSUE #3648: Expected a single document in the stream
### Describe the bug

Hello,

Kubernetes-client cannot read documents that contains one ressource and end with "---", snakeyaml throws exception "expected a single document in the stream".
It used to work with kubernetes-client 4.13.3.

Using Kubernetes-client:4.13.0, this used to work.

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

Using example LoadMultipleDocumentsFromFileExample, modify the file multiple-document-template.yml to keep only one resource and ending the file with "---" : 

```
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    tier: backend
    role: master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    tier: backend
    role: master
---
```

snakeyaml throws exception 

```
expected a single document in the stream
 in 'reader', line 17, column 1:
    apiVersion: v1
    ^
but found another document
 in 'reader', line 33, column 1:
    ---
    ^

	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:114)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:452)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshalYaml(Serialization.java:369)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:191)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:156)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.getItems(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:81)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.getOperations(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:92)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.accept(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:215)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.accept(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:53)
	at com.dassault_systemes.infra.cloud.kubernetes.driver.action.LoadMultipleDocumentsFromFileExampleTest.test(LoadMultipleDocumentsFromFileExampleTest.java:49)
```

### Expected behavior

Kubernetes-client should be able to serialize YAML files that have only one resource and ends with "---".

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

Issue is not related to K8S API.

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Fix #3648 

Serialization.unmarshal doesn't handle the case when YAML contains only
single document but yet contains a leading or trailing document
delimiter(`---`).

Trim YAML document delimiters in case of single documents

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java [hunk 1]
```diff
@@ -152,6 +152,8 @@ public static ObjectMapper yamlMapper() {
     String specFile = readSpecFileFromInputStream(is);
     if (containsMultipleDocuments(specFile)) {
       return (T) getKubernetesResourceList(parameters, specFile);
+    } else if (specFile.contains(DOCUMENT_DELIMITER)) {
```
Comment (manusa) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java:155]: This statement will match things like
```yaml
metadata:
  annotations:
    annotation: ---
```

Comment (manusa) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java:155]: A quick `replaceAll("^---.*$", "")` should probably do the job.

Comment (manusa) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java:155]: We should also be careful with scalars, not sure how this might be interpreted in those cases.

Comment (rohanKanojia) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java:155]: I tried with `replaceAll("^---.*$", "")` but it doesn't seem to replace document delimiters. I checked and yaml string seems to be in this format:

Screenshot from 2022-01-07 15-05-52

`specFile.replaceAll(System.lineSeparator() + "---", "")` seems to work. Shall I update to use this instead?

Comment (manusa) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java:157]: So basically if it`s a single document YAML it can only have line separators:
- beginning
- ending
- both
- none

So these replacements might be applicable:
- For optional beginning delimiter:
  `^---\s?.*?\r?\n`
- For optional ending delimiter:
  `\n---\s?.*?\r?\n?$`

**Review by ParriePierre — APPROVED** [review]
The tests are covering the issue I found. The fix looks fine to me.

**Review by manusa — APPROVED** [review]

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java (hunk 1 above)
Comment (manusa) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java:156]: So after our chat on Friday, it all came down to 
```
      specFile = specFile.replaceAll("^---([ \\t].*?)?\\r?\\n","");
      specFile = specFile.replaceAll("\\n---([ \\t].*?)?\\r?\\n?$","\n");
```

However, I'm checking the spec and this is probably incorrect.
https://yaml.org/spec/1.0/#id2561718

Comment (manusa) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java:156]: So, it's probably better to leave it like this for now, and account for further edge cases in the future.
