### PR TITLE
Fixes #1165: Null parameter values are now handled properly

### LINKED ISSUE #1165: NullPointerException in TemplateOperationsImpl if a parameter value is null
In TemplateOperationsImpl#processLocally. if the map contains a null parameter value a NPE is thrown. 

```
2018-08-01 17:14:51 WARN  ResourceChecker:53 - Exception in checker task
java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240)
	at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:205)
	at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:157)
	at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:59)
	at io.enmasse.controller.common.KubernetesHelper.processTemplate(KubernetesHelper.java:123)
	at io.enmasse.controller.TemplateInfraResourceFactory.createResourceList(TemplateInfraResourceFactory.java:85)
	at io.enmasse.controller.CreateController.handle(CreateController.java:104)
	at io.enmasse.controller.ControllerChain.onUpdate(ControllerChain.java:120)
	at io.enmasse.k8s.api.ResourceChecker.doWork(ResourceChecker.java:48)
	at io.enmasse.k8s.api.ResourceChecker.run(ResourceChecker.java:40)
	at java.lang.Thread.run(Thread.java:748)
```

A solution would be to treat the parameter value as an empty string

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by gastaldi** [comment]
[test]

**Comment by rohanKanojia** [comment]
ok to test

File: kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java [hunk 1]
```diff
@@ -212,4 +213,16 @@ public void testProcessParameterizedNumberTemplate() throws IOException {
...
+
+  @Test
+  public void testShouldNotThrowNullPointerException() {
+    server.expect().withPath("/oapi/v1/namespaces/test/templates/tmpl1").andReturn(200, new TemplateBuilder()
+      .withNewMetadata().withName("tmpl1").endMetadata()
+      .withParameters(new ParameterBuilder().withName("key").build())
+      .build()).once();
+    OpenShiftClient client = server.getOpenshiftClient();
+    KubernetesList list = client.templates().withName("tmpl1").processLocally(Collections.singletonMap("key", (String) null));
+    assertNotNull(list);
```
Comment (bartoszmajsak) [inline kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java]: Can this test be a bit more descriptive? 

- when it shouldn't throw NPE? maybe method name needs a bit more love :)
- if you provided default value to `""` it would be good to cover that as it becomes a contract now

File: openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/TemplateOperationsImpl.java [hunk 2]
```diff
@@ -202,6 +205,12 @@ public KubernetesList processLocally(Map<String, String> valuesMap)  {
             } else {
               throw new IllegalArgumentException("No value available for parameter name: " + parameterName);
             }
+            if (parameterValue == null) {
+              if (logger.isDebugEnabled()) {
```
Comment (rohanKanojia) [inline openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/TemplateOperationsImpl.java]: What's the point to checking whether debug is enabled or not when you're already doing logger.debug?

**Comment by rohanKanojia** [comment]
@gastaldi : Could you please add a line to CHANGELOG.md regarding this fix?

**Comment by rohanKanojia** [comment]
[merge]
