### PR TITLE
Fixes #3880: Synchronize access to map in KubernetesCrudDispatcher

### LINKED ISSUE #3880: Mock Webserver Crash
### Describe the bug

Mock webserver is periodically crashing. I've noticed in CrudDispatcher all access to the map is synchronized, but it is not in KubernetesCrudDispatcher.

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

Use multiple threads to interact with mock webserver

### Expected behavior

Access to backing map is synchronized preventing concurrent modification exceptions

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
SEVERE: MockWebServer[37745] connection from /127.0.0.1 crashed
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:751)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:749)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.fabric8.kubernetes.client.server.mock.KubernetesCrudDispatcher.handleGet(KubernetesCrudDispatcher.java:135)
	at io.fabric8.mockwebserver.crud.CrudDispatcher.dispatch(CrudDispatcher.java:64)
	at io.fabric8.kubernetes.client.server.mock.KubernetesMixedDispatcher.dispatch(KubernetesMixedDispatcher.java:65)
	at okhttp3.mockwebserver.MockWebServer$3.processOneRequest(MockWebServer.java:559)
	at okhttp3.mockwebserver.MockWebServer$3.processConnection(MockWebServer.java:517)
	at okhttp3.mockwebserver.MockWebServer$3.execute(MockWebServer.java:443)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by coopstah13**
The CrudDispatcher map is a synchronized map. The implementation of the standard map operations are already internally synchronized, but it explicitly states that iterating the map in any way should be synchronized. Occasionally in a multi-threaded scenario access to the map results in a ConcurrentModificationException because of a lack of synchronization.

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java [hunk 1]
```diff
@@ -274,7 +279,7 @@ public MockResponse handleWatch(String path) {
     }
     WatchEventsListener watchEventListener = new WatchEventsListener(context, query, watchEventListeners, LOGGER,
       watch -> {
-        synchronized (KubernetesCrudDispatcher.this) {
+        synchronized (map) {
```
Comment (coopstah13) [inline kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java:282]: I wasn't sure of the ramifications of this change, as in, I'm unclear why there was a synchronized block previously the way it was, but I believe it should only be synchronized around the map. I didn't want to use double synchronization.

**Review by oscerd — APPROVED** [review]
