### PR TITLE
fix (kubernetes-client-api) :Add new autoOAuthToken field in Config to differentiate between user and autoconfigured tokens (#4802)

### LINKED ISSUE #4802: config.refresh() erases token specified when building initial config
### Describe the bug

Relates to https://github.com/fabric8io/kubernetes-client/issues/4519

This is essentially the same problem but using a fixed token instead of a kubeconfig file when building the initial configuration.

### Fabric8 Kubernetes Client version

6.3.1

### Steps to reproduce

Instantiate the client using

```
KubernetesClient client = new KubernetesClientBuilder().withConfig(new ConfigBuilder().withMasterUrl("https://url-to-my-kubernetes-master").withCaCertData("my-ca-cert-data").withOauthToken("my-token").build()).build();
```

and also have a file at `/var/run/secrets/kubernetes.io/serviceaccount/token` with some different token.

After 1 minute, calls start failing with `Unauthorized` errors.

### Expected behavior

Calls don't fail after 1 minute

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.23

### Environment

Amazon

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Fix #4802 

+ Add a new string field autoOAuthToken in Config, this field would be
      used by Config internally to store token obtained during
      autoconfiguration process.
+ Remove setOAuthToken references from token interceptors and Config, it
      would only be called by user (during `new ConfigBuilder().withOAuthToken("...")` call)
      whenever custom token is required.
+ getOAuthToken would give most priority to token from provider, then
      actual value of `oauthToken` and finally `autoOAuthToken` value. All
      interceptors would keep using getOAuthToken to get resolved OAuth
      token value

Updated TokenRefreshInterceptor / OpenShiftOAuthInterceptor to match these expectations:

_Orignally posted by @shawkins_:

- [X] if it's a user token(`oauthToken` is set), don't do any refresh logic at all.  
- [X] if we don't have an oauth token provider, then every minute we could do a proactive "soft" refresh the Config (like the current refresh method) - that may do some file reads or even some exec/system calls, so it's best if it's not happening inline with the http requests and if applicable and the token is nearing expiration do the oidc call.  
- [X] If there is an auth failure and there's no user token or token provider we should start with the soft refresh
- [X] if a token is now there and came from the execconfig or something other than the kubeconfig (service account or env), then use it.
- [X] If the token still isn't there or came from the kubeconfig and the kubeconfig provides the appropriate AuthProvider, then we should do the oidc refresh

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [X] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [X] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

File: openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java [hunk 1]
```diff
@@ -94,6 +94,9 @@ public void before(BasicBuilder builder, HttpRequest httpRequest, RequestTags ta
 
   @Override
   public CompletableFuture<Boolean> afterFailure(Builder builder, HttpResponse<?> response, RequestTags tags) {
+    if (config.isTokenNonRefreshable()) {
+      return CompletableFuture.completedFuture(true);
```
Comment (shawkins) [inline openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java:98]: Returning true here and in the other interceptor means to try the request again, but since no modifications have been made on the builder, it would just re-issue the existing request.

Including the token provider in isTokenNonRefreshable could be confusing as it may refresh.  That is:

if token source == user, then do nothing
if token source == provider, then attempt to get the token again and try once more.

**Review by shawkins — CHANGES_REQUESTED** [review]
This looks good.  It's the easiest way to do this with the existing code structure.

- the user OauthTokenProvider will take precedence.
- the user oauthToken will be used next  
- if neither of those were used, then every minute there will be a soft refresh or an open id refresh is the token is near expiration.  The code was already doing this, but didn't check for expiration, so we probably can resolve the main thrust of #2112.  The other issues mentioned on there likely remain.
- on unauthorized failure there will be a last chance refresh

Improvements that can be done later:
- Don't update the Config - move the autoOathToken and related refresh logic off of the Config and onto to the refresh interceptors.  But this requires a lot of changing of how we "refresh" the Config.
- don't re-attempt the request if the token hasn't actually changed from the initial request
- coordinate the refresh #4704 - and perform the time based soft refresh in a non IO thread.

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java [hunk 2]
```diff
@@ -971,12 +979,18 @@ public static String getKeyAlgorithm(String clientKeyFile, String clientKeyData)
     return null;
   }
 
+  public String getUserConfiguredOauthToken() {
```
Comment (shawkins) [inline kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java:982]: This and the getAutoOAuthToken may need jsonignores

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptor.java [hunk 3]
```diff
@@ -84,14 +84,22 @@ public CompletableFuture<Boolean> afterFailure(BasicBuilder headerBuilder, HttpR
   }
 
   private CompletableFuture<Boolean> refreshToken(BasicBuilder headerBuilder) {
+    if (config.getOauthTokenProvider() != null) {
+      String tokenFromProvider = config.getOauthTokenProvider().getToken();
+      if (tokenFromProvider != null && !tokenFromProvider.isEmpty()) {
+        return CompletableFuture.completedFuture(overrideNewAccessTokenToConfig(tokenFromProvider, headerBuilder, config));
+      } else if (config.getUserConfiguredOauthToken() != null && !config.getUserConfiguredOauthToken().isEmpty()) {
```
Comment (shawkins) [inline kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptor.java:91]: this needs to be in a separate block after the oathtokenprovider check

**Comment by shawkins** [comment]
@rohanKanojia @manusa opened a pr against this pr that updates to latest (as of yesterday), and takes the changes a little further https://github.com/rohanKanojia/kubernetes-client/pull/176/commits/d4fba9d42e2956d00e9b94e8cf2866c269e54fc6 - which further clarifies the behavior and tries to localize it better into the TokenRefreshInterceptor.  The only thing that may be odd is that I removed some checks for empty string because they were not being applied consistently - they can of course be added back.

**Comment by shawkins** [comment]
LGTM, should be ready after resolving conflicts.

**Review by shawkins — APPROVED** [review]

**Review by manusa — APPROVED** [review]
