### PR TITLE
fix(vertx): VertxHttpClient uses exclusive Vert.x instance by default

### LINKED ISSUE #6792: Shutdown hook in VertxHttpClientFactory prevents client usage in other shutdown hook
### Describe the bug

This library should not assume that it is in charge of shutting down the Http connection. Instead, this should be left to the client app.
In camel k8s we have we have a 'run' option which can be stopped with ctrl+c, upon which all k8s resources are also deleted from the cluster.

This code causes regression, such that these resources can no longer be deleted when executing our shutdown hook ...

```
    public VertxHttpClientFactory() {
        this(VertxHttpClientFactory.VertxHolder.INSTANCE);
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            if (this.vertx != null) {
                this.vertx.close();
            }

        }));
    }
```

I checked the other http client variants and it seems that vertx is the only one that installs a shutdown hook. Please consider removing this code and instead rely on higher layers to close the k8s client when appropriate.

### Fabric8 Kubernetes Client version

7.0.1

### Steps to reproduce

See: https://issues.apache.org/jira/browse/CAMEL-21621

### Expected behavior

Using this k8s client in a shutdown hook should be valid

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by manusa**
## Description

Fixes #6792

A shared Vert.x instance can still be provided to the VertxHttpClientFactory.

This instance will be shared across the different VertxHttpClient instances.

It's responsibility of the user to handle the Vert.x shared instance lifecycle

/cc @shawkins 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClient.java [hunk 1]
```diff
@@ -122,6 +134,9 @@ public CompletableFuture<HttpResponse<AsyncBody>> consumeBytesDirect(StandardHtt
   @Override
   public void doClose() {
     client.close();
```
Comment (shawkins) [inline httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClient.java:136]: Just in case, a try finally would be good here.

**Review by shawkins — COMMENTED** [review]
Looks good, just one additional thought.

File: httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClient.java (hunk 1 above)
Comment (manusa) [reply httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClient.java:136]: I'm not completely following, do you mean like this:
```
    try {
      client.close();
    } finally {
      if (closeVertx) {
        vertx.close();
      }
    }
```

**Review by shawkins — APPROVED** [review]
LGTM
