### PR TITLE
Fix #2009: Regression `withoutLabel()` stopped to work

### LINKED ISSUE #2009: Regression `withoutLabel()` stopped to work
Regression between `4.1.1` to `4.3.1`

```java
List<ConfigMap> configMapList = Stream.of(
		new ConfigMapBuilder("keep-label-map").addLabel(KEEP_LABEL, null).build(),
		new ConfigMapBuilder("null-label-map").build(),
		new ConfigMapBuilder("arbitrary-label-map").build()
).collect(Collectors.toList());

openshift.configMaps().withoutLabel(KEEP_LABEL).list().getItems().size() == 3

openshift.configMaps().withLabel(KEEP_LABEL).list().getItems().size() == 1

openshift.configMaps().withLabelNotIn(KEEP_LABEL).list().getItems().size() = 2
```

Same goes also for other resources:
```java
openshift.pods().list().getItems().size() == 2

openshift.pods().withoutLabel(OpenShift.KEEP_LABEL).list().getItems().size() == 2

openshift.pods().withLabel(OpenShift.KEEP_LABEL).list().getItems().size() == 1

openshift.pods().withLabelNotIn(OpenShift.KEEP_LABEL).list().getItems().size() == 1
```
Additional info
[1] https://github.com/xtf-cz/xtf/issues/306
[2] https://github.com/xtf-cz/xtf/pull/309

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #2009

### CODE REVIEW

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java [hunk 1]
```diff
@@ -540,7 +540,7 @@ public String getLabelQueryParam() {
           sb.append(",");
         }
         Map.Entry<String, String[]> entry = iter.next();
-        if (entry.getValue() != null) {
+        if (entry.getValue() != null && Utils.isNotNull(entry.getValue())) {
```
Comment (manusa) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java]: First null check is redundant, `Utils#isNotNull`already handles that case
```suggestion
        if (Utils.isNotNull(entry.getValue())) {
```

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java [hunk 2]
```diff
@@ -60,6 +60,17 @@ private Utils() {
...
+  public static <T> boolean isNotNull(T[] refList) {
+    if (refList != null) {
+      for (T ref : refList) {
+        if (ref != null) {
+          return true;
+        }
+      }
+    }
+    return false;
+  }
```
Comment (manusa) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java]: Nit: Can be replaced by a less complex functional and declarative approach
```suggestion
  public static <T> boolean isNotNull(T... refList) {
    return Optional.ofNullable(refList)
      .map(refs -> Stream.of(refs).allMatch(Objects::nonNull))
      .orElse(false);
  }
```

It would also be good to move this function near the rest of `isNull*`methods

Comment (manusa) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java]: Add some Unit Tests to verify and document the behavior of this function:
e.g.
```
  @Test
  @DisplayName("isNotNull, null, should return false")
  public void isNotNullNullTest() {
    // When
    final boolean result = Utils.isNotNull((Object)null);
    // Then
    assertFalse(result);
  }

  @Test
  @DisplayName("isNotNull, some null values, should return false")
  public void isNotNullSomeAreNullTest() {
    // When
    final boolean result = Utils.isNotNull("Not Null", null);
    // Then
    assertFalse(result);
  }

  @Test
  @DisplayName("isNotNull, no null values, should return true")
  public void isNotNullNoneAreNullTest() {
    // When
    final boolean result = Utils.isNotNull("Not Null", "Not Null either");
    // Then
    assertTrue(result);
  }
```

File: kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/UtilsTest.java [hunk 3]
```diff
@@ -110,4 +112,36 @@ public void interpolateStringWithParametersTest() {
     // Then
     assertEquals("This is a \"template string\" and the following is code ${NOT_REPLACED}: '1' === '1'; /* END */", result);
   }
+
+  @Test
+  @DisplayName("isNotNull, null, should return false")
+  public void isNotNull() {
+    // When
+    final boolean result1 = Utils.isNotNullOrEmpty((Map)null);
```
Comment (manusa) [inline kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/UtilsTest.java]: These are not tests for the implemented method `isNotNull`

You can keep these in a sepearete method `isNotNullOrEmpty` (with changed DisplayName too) to add more coverage, but please do add the nullcheck tests for the currently being implemented method `isNotNull`

File: kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/UtilsTest.java [hunk 4]
```diff
@@ -110,4 +112,36 @@ public void interpolateStringWithParametersTest() {
...
+    assertFalse(result1);
+    assertFalse(result2);
+    assertFalse(result3);
+  }
+
+  @Test
+  @DisplayName("isNotNull, some null values, should return false")
+  public void isNotNullSomeAreNullTest() {
+    // When
+    final boolean result = Utils.isNotNullOrEmpty(new String[] {"notNullObj", null, null});
```
Comment (manusa) [inline kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/UtilsTest.java]: Same as the previous comment. We are checking `isNotNull`

**Comment by rohanKanojia** [comment]
retest this please

**Comment by rohanKanojia** [comment]
[merge]
