### PR TITLE
Fix #2189: Change package names of Resource Operation classes in order to avoid duplicates

### LINKED ISSUE #2189: Namespace requires Namespace
Hi,

with 4.10.0 there seems to be an issue with cluster-wide resources. So far, I encountered `io.fabric8.kubernetes.client.KubernetesClientException: Namespace not specified. But operation requires namespace.` when applying the following yaml:

```
apiVersion: v1
kind: Namespace
metadata:
  name: istio-operator   
```

using
```
k8s.load(<yaml as input stream>).createOrReplace()
```

```
Namespace not specified. But operation requires namespace.
io.fabric8.kubernetes.client.KubernetesClientException: Namespace not specified. But operation requires namespace.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.checkNamespace(OperationSupport.java:175)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.getNamespacedUrl(OperationSupport.java:151)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getCompleteResourceUrl(BaseOperation.java:854)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:214)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:169)
	at io.fabric8.kubernetes.client.handlers.core.v1.NamespaceHandler.reload(NamespaceHandler.java:64)
	at io.fabric8.kubernetes.client.handlers.core.v1.NamespaceHandler.reload(NamespaceHandler.java:40)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:251)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:65)

```
I did not look into this yet.

Best regards,
Fabian

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #2189 

+ Changed Package Names of OperationsImp classes
+ Added `@Namespaced` annotation in model classes to distinguish between Namespaced and Non-
   Namespaced resources

### CODE REVIEW

File: kubernetes-model/kubernetes-model-annotator/src/main/java/io/fabric8/kubernetes/annotator/KubernetesCoreTypeAnnotator.java [hunk 1]
```diff
@@ -102,6 +104,26 @@ public void propertyOrder(JDefinedClass clazz, JsonNode propertiesNode) {
     }
   }
 
+  private boolean isResourceNamespaced(JDefinedClass resourceClass) {
+    switch (resourceClass.name()) {
```
Comment (dev-gaur) [inline kubernetes-model/kubernetes-model-annotator/src/main/java/io/fabric8/kubernetes/annotator/KubernetesCoreTypeAnnotator.java:108]: if we can avoid hardcoding strings here and [here](https://github.com/fabric8io/kubernetes-client/blob/29c98553e599abc9e5751acddcef59daf6bdcc41/kubernetes-model/kubernetes-model-annotator/src/main/java/io/fabric8/kubernetes/annotator/KubernetesCoreTypeAnnotator.java#L193), that would be great. Otherwise everything looks good to me.

**Comment by rohanKanojia** [comment]
retest this please

**Comment by rohanKanojia** [comment]
[merge]
