### PR TITLE
Remove deprecated methods from KubernetesClientException class #6629

### LINKED ISSUE #6629: Remove deprecated methods from KubernetesClientException class
## Description

Part of #6602 

The following constructors and methods are deprecated and no longer used, they must be removed the `KubernetesClientException` class:

https://github.com/fabric8io/kubernetes-client/blob/25ecf8460eb132ae2945342b33f64a4240a2b91c/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java#L66-L74

https://github.com/fabric8io/kubernetes-client/blob/25ecf8460eb132ae2945342b33f64a4240a2b91c/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java#L76-L84

https://github.com/fabric8io/kubernetes-client/blob/25ecf8460eb132ae2945342b33f64a4240a2b91c/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java#L162-L173

### PR DESCRIPTION
**Pull request by asharan2buff**
Remove deprecated constructors and methods and ran the tests to ensure nothing is failing

## Description

Fixes #6629 

## Type of change

 - [] Bug fix (non-breaking change which fixes an issue)
 - [] Feature (non-breaking change which adds functionality)
 - [] Breaking change (fix or feature that would cause existing functionality to change
 - [X] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [X] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java [hunk 1]
```diff
@@ -63,25 +63,7 @@ private KubernetesClientException(String message, Throwable t, int code, Status
...
-  /**
-   * @deprecated use {@link #KubernetesClientException(String, Throwable, int, Status, HttpRequest)} instead
-   */
-  @Deprecated
-  public KubernetesClientException(String message, Throwable t, String group, String version, String resourcePlural,
-      String namespace) {
-    this(message, t, -1, null,
-        RequestMetadata.builder().group(group).version(version).plural(resourcePlural).namespace(namespace).build());
-  }
+   // Removed deprecated constructors and methods
```
Comment (rohanKanojia) [inline kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java:66]: Please remove this comment. This should be part of your commit message instead.

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java [hunk 2]
```diff
@@ -159,18 +141,7 @@ public static RuntimeException launderThrowable(OperationInfo spec, Throwable ca
...
-  @Deprecated
-  public static RuntimeException launderThrowable(OperationInfo spec, Status status, Throwable cause) {
-    StringBuilder sb = new StringBuilder();
-    sb.append(describeOperation(spec)).append(" failed.");
-    if (status != null && Utils.isNotNullOrEmpty(status.getMessage())) {
-      sb.append("Reason: ").append(status.getMessage());
-    }
-    return launderThrowable(sb.toString(), cause);
-  }
+   // Removed deprecated constructors and methods
```
Comment (rohanKanojia) [inline kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java:144]: Please remove this comment.
