### PR TITLE
Handle JsonNode fields by adding x-kubernetes-preserve-unknown-fields

### LINKED ISSUE #3683: CRD generator doesn't handle correctly JsonNode type
### Describe the bug

The CRD generator produce an empty object for fields with type `JsonNode`.

### Fabric8 Kubernetes Client version

next (development version)

### Steps to reproduce

Generate the CRD for a class containing a field like:

```java
public JsonNode configuration;
```

the output is:

```yaml
              configuration:
                type: object
```

### Expected behavior

the expected output should be:

```yaml
              configuration:
                type: object
                x-kubernetes-preserve-unknown-fields: true
```

### Runtime

Kubernetes (vanilla), other (please specify in additional context)

### Kubernetes API Server version

1.22.3@latest

### Environment

other (please specify in additional context)

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andreaTP**
## Description
Fix #3683 

## Type of change
 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [X] Breaking change (fix or feature that would cause existing functionality to change ( the public API of `AbstractJsonSchema` changed, although I guess it's ok since is still in preview)
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [X] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

File: crd-generator/api/src/test/java/io/fabric8/crd/example/json/ContainingJsonStatus.java [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package io.fabric8.crd.example.json;
+
+public class ContainingJsonStatus {
```
Comment (metacosm) [inline crd-generator/api/src/test/java/io/fabric8/crd/example/json/ContainingJsonStatus.java:18]: You could just use `Void` if you don't need a status 😉

File: crd-generator/api/src/test/java/io/fabric8/crd/example/json/ContainingJson.java [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+ */
+package io.fabric8.crd.example.json;
+
+import io.fabric8.kubernetes.client.CustomResource;
+import io.fabric8.kubernetes.model.annotation.Group;
+import io.fabric8.kubernetes.model.annotation.Version;
+
+@Group("containingjson.fabric8.io")
+@Version("v1alpha1")
+public class ContainingJson extends CustomResource<ContainingJsonSpec, ContainingJsonStatus> {
```
Comment (metacosm) [inline crd-generator/api/src/test/java/io/fabric8/crd/example/json/ContainingJson.java:24]: Use `Void` for the status parameter type if you're not interested in it.

**Review by metacosm — APPROVED** [review]
LGTM

File: crd-generator/api/src/test/java/io/fabric8/crd/example/json/ContainingJsonStatus.java (hunk 1 above)
Comment (andreaTP) [reply crd-generator/api/src/test/java/io/fabric8/crd/example/json/ContainingJsonStatus.java]: removed 👍

File: crd-generator/api/src/test/java/io/fabric8/crd/example/json/ContainingJson.java (hunk 2 above)
Comment (andreaTP) [reply crd-generator/api/src/test/java/io/fabric8/crd/example/json/ContainingJson.java]: fixed 👍

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by andreaTP** [comment]
rebased, should be ready to merge! 🙂
