### PR TITLE
fix: added BOOKMARK as a type in Watcher enum

### LINKED ISSUE #2171: [Feature] Support BOOKMARK events
Kubernetes Server API is able to send regulary BOOKMARK events :

https://kubernetes.io/docs/reference/using-api/api-concepts/#watch-bookmarks

We could imagine that :

```java
client.namespaces()
  .withResourceVersion(resourceVersion)
  .watch(allowBookmarks, watcher)
``` 

And may be also an option to automatically restart a watch from a Bookmark if it is the last received event.

```java
client.namespaces()
  .withResourceVersion(resourceVersion)
  .watch(allowBookmarks, autoRestartWatchFromBookmarkOn410, watcher)
``` 

```java
        class KubernetesObjectWatcher implements Watcher<Namespace> {

            @Override
            public void eventReceived(Action action, Namespace kubernetesObject) {
                if (action.equals(Action.BOOKMARK)) {
                  // Do some action like storing Resource Version found in kubernetesObject
                }
            }

            @Override
            public void onClose(KubernetesClientException e) {
              ...
            }
        }
```

Exemple in the GO client :  

https://github.com/kubernetes/client-go/blob/ce0298a60b3c4651540b2beaf8f9e98a871ab2a3/tools/cache/reflector.go

https://github.com/kubernetes/client-go/blob/ce0298a60b3c4651540b2beaf8f9e98a871ab2a3/tools/cache/reflector.go#L479

https://github.com/kubernetes/client-go/blob/ce0298a60b3c4651540b2beaf8f9e98a871ab2a3/tools/cache/reflector.go#L517

https://github.com/kubernetes/client-go/blob/ce0298a60b3c4651540b2beaf8f9e98a871ab2a3/tools/cache/reflector.go#L266

### PR DESCRIPTION
**Pull request by laxmikantbpandhare**
## Description
Fix  #2171 - Support BOOKMARK events

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by rohanKanojia** [comment]
Please add a test in WatchTest regarding watch event of type bookmark

**Review by jmrodri — APPROVED** [review]
/lgtm

**Comment by laxmikantbpandhare** [comment]
> Please add a test in WatchTest regarding watch event of type bookmark

@rohanKanojia - I added the test for BOOKMARK event.

File: kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java [hunk 1]
```diff
@@ -276,4 +277,40 @@ private static WatchEvent outdatedEvent() {
         "410: The event in requested index is outdated and cleared (the requested history has been cleared [3/1]) [2]")
       .build()).build();
   }
+
+
+  @Test
+  @DisplayName("TryWithResources, connects and receives event then receives GONE, should receive first event and then close")
```
Comment (rohanKanojia) [inline kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java:283]: This description seems to be copied from `testTryWithResourcesConnectsThenReceivesEvent` Could you please update this?

https://github.com/fabric8io/kubernetes-client/blob/08261fba6c9306eb063534ec2320e9166f85c71c/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java#L65

Comment (laxmikantbpandhare) [reply kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java:283]: yes, I saw and kept as it is but now modified it as below.

```
  @DisplayName("TryWithResources, connects and receives event then receives GONE, should receive BOOKMARK event and then close it")
```

**Comment by rohanKanojia** [comment]
Also, I would appreciate it if you could add some documentation regarding using watch with bookmarks in watch options section of CHEATSHEET[0]

[0] https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#watch-options

**Review by manusa — APPROVED** [review]
