### PR TITLE
[crd-generator] Fix inconsistent additionalPrinterColumns jsonPath

### LINKED ISSUE #4610: Inconsistent additionalPrinterColumns jsonPath
### Describe the bug

I have a class defined like:

```java
@JsonInclude(JsonInclude.Include.NON_NULL)
@Buildable(builderPackage = "io.fabric8.kubernetes.api.builder")
public class DeploymentSpec {

    @PrinterColumn(name = "CONNECTOR_TYPE_ID")
    private String connectorTypeId;
}
```

And such class is used in bot the spec and the status of a resource.

### Fabric8 Kubernetes Client version

5.12.4

### Steps to reproduce

Generate CRDs

### Expected behavior

The generated CRD should always use the same path to describe the CONNECTOR_TYPE_ID column.
The resulted CRD may get amended at every build, i.e:

image

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

```xml        
        <kubernetes-client.version>5.12.3</kubernetes-client.version>
        <java-operator-sdk.version>3.1.1</java-operator-sdk.version>
        <quarkus.version>2.11.2.Final</quarkus.version>
        <quarkus-operator-sdk.version>4.0.1</quarkus-operator-sdk.version>
        <sundrio.version>0.50.2</sundrio.version>
```

### PR DESCRIPTION
**Pull request by andreaTP**
## Description
This is a proposal to fix #4610 

After this fix, `additionalPrinterColumns` with different paths will be emitted with colliding names. I'm not sure if this has implications.

## Type of change
 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [X] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/AddAdditionPrinterColumnDecorator.java [hunk 1]
```diff
@@ -40,41 +42,42 @@ public AddAdditionPrinterColumnDecorator(String name, String version, String typ
 
   @Override
   public void andThenVisit(CustomResourceDefinitionVersionFluent<?> spec) {
-    Predicate<CustomResourceColumnDefinitionBuilder> matchingColumn = col -> col.getName() != null && col.getName().equals(columnName);
+    Predicate<CustomResourceColumnDefinitionBuilder> matchingColumn = col -> col.getName() != null
+        && col.getName().equals(columnName) && col.getJsonPath() != null && col.getJsonPath().equals(path);
```
Comment (andreaTP) [inline crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/AddAdditionPrinterColumnDecorator.java:46]: Just highlighting the "real change" in this PR.

**Review by lburgazzoli — APPROVED** [review]
I don't know enough about the details so LGTM :)

File: crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/AddAdditionPrinterColumnDecorator.java (hunk 1 above)
Comment (metacosm) [reply crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/AddAdditionPrinterColumnDecorator.java:46]: Perhaps we should issue a warning when we encounter such a situation?

Comment (andreaTP) [reply crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/AddAdditionPrinterColumnDecorator.java:46]: I checked the behavior, and it looks consistent to me without the need for a warning.
Using the "Joke" CRD used in the tests and created a corresponding "Joke" CR:

```yaml
apiVersion: "samples.javaoperatorsdk.io/v1alpha1"
kind: JokeRequest
metadata:
  name: jr-any
spec:
  category: Any
status:
  category: Pun
```

the output of `kubectl get` seems fine to me:
Screenshot 2022-11-29 at 10 47 21

**Comment by andreaTP** [comment]
rebased and now this diff looks great 🙂 cc. @manusa

**Review by manusa — APPROVED** [review]
