### PR TITLE
fix #3848: Add queue support (cluster level) for Volcano extension

### LINKED ISSUE #3848: Volcano extension doesn't support queue API
### Describe the bug

```
[info]   io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.49.2:8443/apis/scheduling.volcano.sh/v1beta1/namespaces/default/queues. Message: Not Found.
```

It should be `https://192.168.49.2:8443/apis/scheduling.volcano.sh/v1beta1/queues`.

We need to change queue to `Cluster` level rather than `Namespaced`:
https://github.com/fabric8io/kubernetes-client/blob/9d074219b4c3ab4e5921c4f22e3c8f4289c6c698/extensions/volcano/generator-v1beta1/cmd/generate/generate.go#L33

### Fabric8 Kubernetes Client version

other (please specify in additional context)

### Steps to reproduce

```
      String queueName = "queue1";
      Queue queue = Utils.buildDefaultQueues(queueName);
      volcanoClient.queues().createOrReplace(queue);
```

### Expected behavior

create cluster level queue

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.22.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
[info]   io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.49.2:8443/apis/scheduling.volcano.sh/v1beta1/namespaces/default/queues. Message: Not Found.
```

### Additional context

Since
- 5.11.0 +
- 5.12.0 +

### PR DESCRIPTION
**Pull request by Yikun**
## Description

This patch fix the volcano queue type, it should be `Cluster`.
- Fix Queue type: change `schemagen.Namespaced` to `schemagen.Cluster`
- Add example for queue create, and it works as integrations test in real K8S.
- Adapt volcano queue test

Closes: https://github.com/fabric8io/kubernetes-client/issues/3848

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by Yikun** [comment]
cc @rohanKanojia @oscerd @manusa @william-wang

File: extensions/volcano/examples/src/main/java/io/fabric8/volcano/examples/v1beta1/QueueCreate.java [hunk 1]
```diff
@@ -0,0 +1,52 @@
+/**
+ * Copyright (C) 2015 Red Hat, Inc.
```
Comment (william-wang) [inline extensions/volcano/examples/src/main/java/io/fabric8/volcano/examples/v1beta1/QueueCreate.java:2]: please update the Copyright to the right one.

**Comment by Yikun** [comment]
cc @rohanKanojia Would you mind take a look? Thanks!

**Review by rohanKanojia — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Review by manusa — APPROVED** [review]

**Comment by Yikun** [comment]
Thanks for review! @manusa @oscerd @rohanKanojia 

Could this be a fix in 5.12.X?

**Comment by manusa** [comment]
I added a tentative label, but I'm unsure when/if we'll release.

**Comment by Yikun** [comment]
@manusa Thanks! I will keep watching follow releases!
