### PR TITLE
Fix #2265: Refactor SubjectAccessReview API

### LINKED ISSUE #2191: Revisit SubjectAccessReview DSL support
while fixing tests in #2186 , I noticed that `SubjectAccessReviewDSLImpl` is not implemented properly.    
Even tests are not written properly. I'm not sure what this statement is trying to do:

https://github.com/fabric8io/kubernetes-client/blob/509a2e857353c1586373b09d90ab2c167febbd64/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/SubjectAccessReviewAuthTest.java#L73

Maybe some Work in progress stuff got merged and we forgot to fix it. We should probably revisit this and implement it properly

### LINKED ISSUE #2265: InAnyNamespace uses invalid api endpoint for SelfSubjectAccessReviews
I am trying to verify if the current context user has permissions to create a deployment in a given namespace
```java
client = new DefaultKubernetesClient(new ConfigBuilder().withMasterUrl(masterUrl).build());


    SelfSubjectAccessReview review = new SelfSubjectAccessReviewBuilder().withNewSpec()
        .withNewResourceAttributes()
        .withNamespace("test")
        .withResource("deployment")
        .withVerb("create")
        .endResourceAttributes()
        .endSpec()
        .build();
    review = client.subjectAccessReviewAuth().inAnyNamespace().create(review);
```

Which causes this error
```shell
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.docker.internal:6443/apis/authorization.k8s.io/v1/namespaces/test/selfsubjectaccessreviews. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
```

It seems like there shouldn't be a /namespaces/ in the endpoint as 
Running `kubectl --v=8 auth can-i create deployments --namespace test` shows that the endpoint is `https://kubernetes.docker.internal:6443/apis/authorization.k8s.io/v1/selfsubjectaccessreviews`.

Is there a reason namespaces is set to true when instantiating a Createable for inAnyNamespace as seen here? 
```java
public Createable<SelfSubjectAccessReview, SelfSubjectAccessReview, DoneableSelfSubjectAccessReview> inAnyNamespace() {
    return (new SubjectAccessReviewDSLImpl(this.context, namespace, "selfsubjectaccessreviews", true)).self();
  }
```
since that is what seems to be causing the endpoint to include /namespaces/

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fixes #2265 

+ Added new entrypoint authorization() into DSL which only allows create() operations
+ Removed old subjectAccessReviewAuth() API

This should also fix #2191

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] Feature (non-breaking change which adds functionality)
 - [X] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [X] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [X] I tested my code in Kubernetes
 - [X] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CreateOnlyResourceOperations.java [hunk 1]
```diff
@@ -13,18 +13,9 @@
...
-import io.fabric8.openshift.api.model.LocalSubjectAccessReview;
-import io.fabric8.openshift.api.model.LocalSubjectAccessReviewFluentImpl;
-import io.fabric8.openshift.api.model.SubjectAccessReviewResponse;
 
-public abstract class CreateableLocalSubjectAccessReview extends
-  LocalSubjectAccessReviewFluentImpl<CreateableLocalSubjectAccessReview>
-  implements
-  Doneable<SubjectAccessReviewResponse>,
-  Createable<LocalSubjectAccessReview, SubjectAccessReviewResponse, CreateableLocalSubjectAccessReview> {
+public interface CreateOnlyResourceOperations<T, D> extends Createable<T, T, D> {
```
Comment (manusa) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CreateOnlyResourceOperations.java:20]: This interface seems to be redundant now since it's only extending Creatable and not adding any methods. Why keep it?

File: openshift-client/src/main/java/io/fabric8/openshift/client/OpenshiftSubjectAccessOperations.java [hunk 2]
```diff
@@ -13,18 +13,10 @@
...
-import io.fabric8.openshift.api.model.SubjectAccessReview;
-import io.fabric8.openshift.api.model.SubjectAccessReviewFluentImpl;
 import io.fabric8.openshift.api.model.SubjectAccessReviewResponse;
 
-public abstract class CreateableSubjectAccessReview extends
-  SubjectAccessReviewFluentImpl<CreateableSubjectAccessReview>
-  implements
-  Doneable<SubjectAccessReviewResponse>,
-  Createable<SubjectAccessReview, SubjectAccessReviewResponse, CreateableSubjectAccessReview> {
+public interface OpenshiftSubjectAccessOperations<T> {
```
Comment (manusa) [inline openshift-client/src/main/java/io/fabric8/openshift/client/OpenshiftSubjectAccessOperations.java:20]: Different approach to https://github.com/fabric8io/kubernetes-client/pull/2400#discussion_r474025692

Again, why not just ditch the interface and use Creatable instead in the implementing class?

File: openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftLocalSubjectAccessReviewOperationsImpl.java [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+public class OpenShiftLocalSubjectAccessReviewOperationsImpl extends OperationSupport implements Createable<LocalSubjectAccessReview, SubjectAccessReviewResponse, DoneableLocalSubjectAccessReview>, Namespaceable<OpenShiftLocalSubjectAccessReviewOperationsImpl> {
+  private String subjectAccessApiGroupName;
+  private String subjectAccessApiGroupVersion;
+  private String plural;
+
+  public OpenShiftLocalSubjectAccessReviewOperationsImpl(OkHttpClient client, Config config, String apiGroupName, String apiGroupVersion, String plural) {
+    this(new OperationContext().withOkhttpClient(client).withConfig(config), apiGroupName, apiGroupVersion, plural);
+    this.subjectAccessApiGroupName = apiGroupName;
+    this.subjectAccessApiGroupVersion = apiGroupVersion;
+    this.plural = plural;
```
Comment (manusa) [inline openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftLocalSubjectAccessReviewOperationsImpl.java:41]: This is redundant, previous statement already takes care of this. I think you can also declare the fields final.

Comment (manusa) [inline openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftLocalSubjectAccessReviewOperationsImpl.java:41]: This is redundant, previous statement already takes care of this. I think you can also declare the fields final.

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CreateOnlyResourceOperationsImpl.java [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+
+import java.io.IOException;
+import java.util.concurrent.ExecutionException;
+
+public class CreateOnlyResourceOperationsImpl<T, D> extends OperationSupport implements io.fabric8.kubernetes.client.dsl.Createable<T, T, D> {
+  private Class<T> subjectAccessRequestClass;
+
+  public CreateOnlyResourceOperationsImpl(OkHttpClient client, Config config, String apiGroupName, String apiGroupVersion, String plural, Class<T> subjectAccessRequestClass) {
+    this(new OperationContext().withOkhttpClient(client).withConfig(config), apiGroupName, apiGroupVersion, plural, subjectAccessRequestClass);
+    this.subjectAccessRequestClass = subjectAccessRequestClass;
```
Comment (manusa) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CreateOnlyResourceOperationsImpl.java:32]: Sames as: https://github.com/fabric8io/kubernetes-client/pull/2400/files#r475370434

**Review by manusa — APPROVED** [review]

**Comment by manusa** [comment]
[merge]
