### PR TITLE
[java-gen] Adding support for nullable fields generation

### LINKED ISSUE #3975: [java-gen] - Add support for nullable fields generation
### Describe the bug

CRD attributes should be generated according to the specs with respect to the `nullable` property value, see https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting-and-nullable

As stated in https://github.com/fabric8io/kubernetes-client/issues/3869#issuecomment-1042058749, this issue is tracking the changes needed to support the generation of nullable fields, by adding the related annotation when generating the field declaration.

CC @andreaTP 

### Fabric8 Kubernetes Client version

next (development version)

### Steps to reproduce

1. execute `cd java-generator ; mvn clean install`
2. the generated Java model - for instance by ApprovalTest - doesn't handle fields that don't define a `nullable` property. 

### Expected behavior

According to the specs (https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting-and-nullable) and to what suggested in https://github.com/fabric8io/kubernetes-client/issues/3869#issuecomment-1042058749, fields that don't define the `nullable` property or have it set to `false` should be annotated accordingly in order to be properly serialized/deserialized at runtime. 

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

k8s runtime and execution environment are not relevant.

### PR DESCRIPTION
**Pull request by fabiobrz**
## Description
This PR is proposing changes which are required in order to provide support for nullable/non-nullable fields generation in the Java model.

Fixes #3975 

## Type of change
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java [hunk 1]
```diff
@@ -208,6 +208,16 @@ public GeneratorResult generateJava() {
...
         }
+
+        if (!prop.isNullable) {
+          // from https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting-and-nullable :
+          // "_null values for fields that either don't specify the nullable flag, or give it a false
+          // value, will be pruned before defaulting happens. If a default is present, it will be applied._"
+          objField.addAnnotation(
+              new SingleMemberAnnotationExpr(
+                  new Name("com.fasterxml.jackson.annotation.JsonSetter"),
+                  new NameExpr("nulls=com.fasterxml.jackson.annotation.Nulls.SKIP")));
```
Comment (andreaTP) [inline java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java:219]: nitpick
```suggestion
                  new NameExpr("nulls = com.fasterxml.jackson.annotation.Nulls.SKIP")));
```

File: java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java [hunk 2]
```diff
@@ -390,6 +398,51 @@ void testObjectWithPreservedFields() {
...
+    FieldDeclaration actualO1Field = o1Field.get();
+    Optional<AnnotationExpr> nullableAnnotation = actualO1Field
+        .getAnnotationByName("com.fasterxml.jackson.annotation.JsonSetter");
+    assertFalse(nullableAnnotation.isPresent());
+
+    Optional<FieldDeclaration> o2Field = clzT.get().getFieldByName("o2");
+    assertTrue(o2Field.isPresent());
+    FieldDeclaration actualO2Field = o2Field.get();
+    nullableAnnotation = actualO2Field.getAnnotationByName("com.fasterxml.jackson.annotation.JsonSetter");
+    assertTrue(nullableAnnotation.isPresent());
```
Comment (andreaTP) [inline java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java:440]: can we check the actual value of nulls of JsonSetter too?

File: java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java (hunk 1 above)
Comment (andreaTP) [inline java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java:219]: this encoding looks correct to me, but I would like someone else opinion to be sure, cc. @manusa @metacosm

File: java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java [hunk 3]
```diff
@@ -208,6 +208,16 @@ public GeneratorResult generateJava() {
                   new StringLiteralExpr(
                       prop.getDescription().replace("\"", "\\\""))));
         }
+
+        if (!prop.isNullable) {
```
Comment (andreaTP) [inline java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java:212]: I miss to see an `else` branch here, is it intended?
e.g. if the field is marked as nullable we probably want to annotate it with something like: `JsonSetter( nulls = Nulls.SET)`

Have you already considered this case?

**Review by andreaTP — CHANGES_REQUESTED** [review]
Great start!

A few comments and I would like another pair of eyes to look at this, but seems really good!
Thanks @fabiobrz !

File: java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java (hunk 1 above)
Comment (fabiobrz) [reply java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java]: Done, thanks!

File: java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java (hunk 2 above)
Comment (fabiobrz) [reply java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java:445]: +1, done.

File: java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java (hunk 3 above)
Comment (fabiobrz) [reply java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java:212]: You're right,, branch added setting `Nulls.SET`, as per the k8s specs [1] and the Jackson implementation [2].
Defaulting implementation will change this a bit once it's in, but I guess it's expected.

[1]
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting-and-nullable

[2]
https://fasterxml.github.io/jackson-annotations/javadoc/2.10/com/fasterxml/jackson/annotation/Nulls.html

**Comment by fabiobrz** [comment]
> A few comments and I would like another pair of eyes to look at this, but seems really good! Thanks @fabiobrz !

Thanks @andreaTP - I've gone through you'r comments, let me know what you think.
BTW I noticed the CI checks failed one Karaf related test, but this seems intermittent to me. WDYT?

File: java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java (hunk 1 above)
Comment (manusa) [reply java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java]: This means that the default value is preserved in case it existed which should be aligned with what's stated in this epigraph: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting-and-nullable

**Review by manusa — APPROVED** [review]
