### PR TITLE
Expands the HTTP interceptor API to include a call back for failed connection attempts

### LINKED ISSUE #6143: Interceptor not invoked when connection refused
### Describe the bug

I'm trying to migrate the Apache Flink kubernetes operator from using an [OkHttp interceptor](https://github.com/apache/flink-kubernetes-operator/blob/main/flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesClientMetrics.java) to using the new fabric8 http interceptor API. Which seems to have gone reasonably smoothly apart from one final test: https://github.com/apache/flink-kubernetes-operator/blob/aaf26aec8bdfedff0116c5897bd89b17b4454606/flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/KubernetesClientMetricsTest.java#L376

Which is failing because `afterFailure` is not invoked when there is no http response (I think). I've added a failing [unit test](https://github.com/SamBarker/kubernetes-client/blob/a60dc211cb67cfa358be9ec568483c8cae444f1d/kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractInterceptorTest.java#L175-L195) in kubernetes-client which demonstrates what I expected to work.

So I'm wondering if the test I've written should work? Or have I missed something in how the API is expected to be used

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

1. checkout https://github.com/SamBarker/kubernetes-client/tree/afterFailureInvocation
1. run `io.fabric8.kubernetes.client.http.AbstractInterceptorTest#afterHttpFailureRemoteOffline` (I've been testing with the OkHttp client but I don't think it matters)
1. see test fail

### Expected behavior

The test passes

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SamBarker**
## Description

Expands the HTTP interceptor API to include a call back for failed connection attempts as discussed in #6143 

Fixes #6143

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

Depends on the definition of breaking change as it adds a new `default` method to an interface which could be seen as a breaking change for any implementation that already has that method defined but practically speaking this is backwards compatible. 

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java [hunk 1]
```diff
@@ -108,6 +108,13 @@ private CompletableFuture<HttpResponse<AsyncBody>> consumeBytesOnce(StandardHttp
     final Consumer<List<ByteBuffer>> effectiveConsumer = consumer;
 
     CompletableFuture<HttpResponse<AsyncBody>> cf = consumeBytesDirect(effectiveRequest, effectiveConsumer);
+    cf.exceptionally(throwable -> {
+      builder.interceptors.forEach((s, interceptor) -> interceptor.afterConnectionFailure(effectiveRequest, throwable));
+      if (throwable instanceof CompletionException) {
+        throw (CompletionException) throwable;
+      }
```
Comment (SamBarker) [inline kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java:115]: sonar is complaining this branch is untested, but I can't work out a way to inject a `CompletionException`.  Any pointers gratefully received.

Comment (SamBarker) [reply kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java:115]: Came up with https://github.com/SamBarker/kubernetes-client/commit/43f88fab5597a3d85bfedda2dab1033259f238de  which does trigger the branch using the Jetty client.

Comment (SamBarker) [reply kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java:115]: apparently not according to sonar. It seemed to work in the debugger locally.

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/Interceptor.java [hunk 2]
```diff
@@ -84,4 +97,15 @@ default CompletableFuture<Boolean> afterFailure(HttpRequest.Builder builder, Htt
     return afterFailure((BasicBuilder) builder, response, tags);
   }
 
+  /**
+   * Called after a connection attempt fails.
+   * <p>
+   * This method will be invoked on each failed connection attempt so can be invoked multiple times for the same request.ID.
```
Comment (manusa) [inline kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/Interceptor.java:103]: I'm not sure if this information might end up being misleading.
What's the motivation to add it?

What I mean is that users (who don't read carefully) might assume the opposite (for a given operation, for each connection failure, request id will be the same) which isn't true.

File: httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java [hunk 3]
```diff
@@ -103,6 +103,11 @@ public void onContent(Response response, ByteBuffer content, Callback callback)
     }
   }
 
+  @Override
+  public void onFailure(Response response, Throwable failure) {
+    asyncResponse.completeExceptionally(failure);
```
[the remark this answers is not in the document]
Comment (manusa) [reply httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java:108]: I can't remember, but I do recall using the Adapter to avoid implementing all methods.
It's certainly strange that the onFailure wasn't implemented before. However, the HttpClient behavior did change a little after the original implementation (especially the retries part).

Anyway, it does seem OK to have this.

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java (hunk 1 above)
Comment (SamBarker) [reply kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java]: Urgh yeah I hadn't thought about the multiple modules pushing in different directions. Sonar only reports a single number on the `StandardHttpClient` so a bit hard to know. I suspect on balance its probably better to have the test than not but I only added it to try and pass the coverage stats for the PR so not wedded to it as the core flows are tested.

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/Interceptor.java (hunk 2 above)
Comment (SamBarker) [reply kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/Interceptor.java]: Yeah I think its so I've removed it. 

While trying to update it I attempted to write a test that caused an unclean disconnect from a websocket connection but wasn't able to. If you think thats important to have do you have any thoughts on how I might trigger it?

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/Interceptor.java [hunk 4]
```diff
@@ -63,7 +70,10 @@ default AsyncBody.Consumer<List<ByteBuffer>> consumer(AsyncBody.Consumer<List<By
   }
 
   /**
-   * Called after a websocket failure or by default from a normal request
+   * Called after a websocket failure or by default from a normal request.
+   * <p>
+   * Failure is determined by HTTP status code and will be invoked in addition to {@see Interceptor#after(HttpRequest,
```
Comment (manusa) [inline kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/Interceptor.java:75]: This Javadoc is not ok, you probably meant `@link` instead of `@see`?

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/Interceptor.java [hunk 5]
```diff
@@ -75,7 +85,10 @@ default CompletableFuture<Boolean> afterFailure(BasicBuilder builder, HttpRespon
 
   /**
    * Called after a non-websocket failure
-   *
+   * <p>
+   * Failure is determined by HTTP status code and will be invoked in addition to {@see Interceptor#after(HttpRequest,
```
Comment (manusa) [inline kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/Interceptor.java:89]: This Javadoc is not ok, you probably meant `@link` instead of `@see`?

**Review by manusa — CHANGES_REQUESTED** [review]
Besides the Javadoc issue I think everything else looks OK.

@shawkins any comments?

BTW, even though this is adding a feature, I'm going to consider it as a bug fix since it's addressing the lack of feature parity of Fabric8-OkHttp interceptors.

This way we can include it as part of #6097 and release it in 6.13.2

File: httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (shawkins) [reply httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java:108]: It looks like overriding onComplete ensured timely completion - but does not have appropriate exception handling. 

What we are probably looking for here instead is using onComplete Result.getRequestFailure - that maps most closely to these types of exceptions. There is also Result.getResponseFailure which should be the same as what is passed to onFailure.

**Review by shawkins — COMMENTED** [review]
Overall looks good, but we may need more refinement of Jetty exception handling.

File: httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (SamBarker) [reply httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java:108]: Oh this gets fun 😅 

Updating `onComplete` to respect `Result.isSucceeded()` or `Result.isFailed()` causes [the expectContinue](https://github.com/SamBarker/kubernetes-client/blob/25ecf8460eb132ae2945342b33f64a4240a2b91c/kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpPostTest.java#L130) test to fail, because Jetty considers a 404 in response to a request with `Expect=100-continue` to be a [failure](https://github.com/jetty/jetty.project/blob/2881fe9ab569946f36ec9dac6c59205b4b969007/jetty-client/src/main/java/org/eclipse/jetty/client/ContinueProtocolHandler.java#L84). So i've tried adding `server.expect().post().withPath("/post-expect-continue").andReply(100, request -> "").always();` which causes the server to reply appropriately to the `POST` request. However that breaks `expectContinue` for `jetty`, `OkHttp` and `VertX` (there doesn't seem to be a JDK version 👀 ) clients tests 😢 .

In the jetty case the test now fails because the response is considered pending and there is no further `demand` so the request future never completes. I haven't debugged the others to work out whats going wrong but I suspect its something similar. 

Reading [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/100) on `100-continue` suggests the jetty implementation is wrong as it attaches the body to the `POST` request at the same time as the `Expect=100-continue` header. Whereas MDN suggests that it should send `Expect=100-continue` and wait for the response to  that before continuing by sending the body. 

I'm nothing like close enough to the details of the Kube API server to understand if 100-continue is commonly used or if it has a problem with including the `POST` body on the initial request. However this is starting to feel like a rabbit hole and not really in scope for this PR and thus what the implications of this are in practice. 

Thoughts @manusa, @shawkins ?

**Comment by SamBarker** [comment]
> BTW, even though this is adding a feature, I'm going to consider it as a bug fix since it's addressing the lack of feature parity of Fabric8-OkHttp interceptors.
This way we can include it as part of https://github.com/fabric8io/kubernetes-client/issues/6097 and release it in 6.13.2

Sounds great from my POV

File: httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (SamBarker) [reply httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java:108]: Ahh the JDK client explicitly disables the `expectContinue` test.

[the remark this answers is not in the document]
Comment (SamBarker) [reply httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java:108]: > Reading [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/100) on 100-continue suggests the jetty implementation is wrong as it attaches the body to the POST request at the same time as the Expect=100-continue header. Whereas MDN suggests that it should send Expect=100-continue and wait for the response to that before continuing by sending the body.

After further debugging the jetty Impl is right, jetty handles delaying the body if the Expect header is set but I'm still not seeing the request complete.

[the remark this answers is not in the document]
Comment (SamBarker) [reply httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java:108]: Hmm turns out I was very wrong about what was going on after much debugging I have 
https://github.com/fabric8io/kubernetes-client/pull/6197/files 

Which changes the default socketPolicy for the mockWebserver to `EXPECT_CONTINUE` from `KEEP_OPEN`. I haven't found a way to make it conditional on the headers as its too late by the time dispatch is called. I'm not at all sure what implications that change has.

I'm happy to merge that PR into this one if preferred but I think they are really independent. I'm happy to clean up that PR and its description and or raise an issue to cover it if the consensus is to keep it independent.

[the remark this answers is not in the document]
Comment (manusa) [reply httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java:108]: Nice work, I think it's better to keep them separate.

**Comment by SamBarker** [comment]
I plan to clean this up once https://github.com/fabric8io/kubernetes-client/pull/6197 is merged, but I think the coverage issues will go away once thats merged.

**Comment by manusa** [comment]
Hi @SamBarker,
#6197 is finally in. Is there something else left to do on this PR? Shall we merge it too?

**Comment by SamBarker** [comment]
> Hi @SamBarker,
> 
> #6197 is finally in. Is there something else left to do on this PR? Shall we merge it too?

I've added an extra commit to get the sonar coverage report passing so yes! Let's get this merged.

Any info on a timeline for the next 6.13 release?

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
> Any info on a timeline for the next 6.13 release?

I was just waiting for this one (#6097), so probably in a couple of hours or early Monday.

**Review by manusa — APPROVED** [review]
LGTM, thx!
