### PR TITLE
#1266 Fixing NPE which occurs in 'ImpersonatorInterceptor' when optional 'Impersonate-Group' header is not set

### LINKED ISSUE #1266: Not setting optional `Impersonate-Group` results in NPE in ImpersonatorInterceptor
Currently, if `Impersonate-User` header is set in the request config, not setting `optional` [1] `Impersonate-Group` header results in NPE in `ImpersonatorInterceptor` [2]

[1] https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation
[2] https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ImpersonatorInterceptor.java#L47

### PR DESCRIPTION
**Pull request by ibuziuk**
Issue - https://github.com/fabric8io/kubernetes-client/issues/1266

### CHANGELOG

* Fix #1266 : Not setting optional `Impersonate-Group` results in NPE in `ImpersonatorInterceptor`

### CODE REVIEW

**Comment by oscerd** [comment]
Can you please add a comment in the CHANGELOG? Thanks

**Comment by oscerd** [comment]
ok to test

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java [hunk 1]
```diff
@@ -277,6 +277,10 @@ public static boolean isNotNullOrEmpty(String str) {
     return !isNullOrEmpty(str);
   }
 
+  public static boolean isNotNullOrEmpty(String[] array) {
+    return !(array == null || array.length == 0);
+}
+
```
Comment (rohanKanojia) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java]: indentation slightly off here ;-)

**Comment by ibuziuk** [comment]
@oscerd have added CHANGELOG note in the PR description. Should I also update `CHANGELOG.md` ?
if yes,  what version should I refer to ?

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java (hunk 1 above)
Comment (ibuziuk) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java]: oh, sorry - my bad

Comment (ibuziuk) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java]: fixed

**Comment by rohanKanojia** [comment]
[merge]

**Comment by ibuziuk** [comment]
@rohanKanojia @oscerd do you happen to know when it is planned to release `4.1.1`

**Comment by oscerd** [comment]
@rohanKanojia I believe we can release this week

**Comment by rohanKanojia** [comment]
@oscerd : ah, ok. I was wondering to include model upgrade (on which I'm working right now) also as a part of next release.

**Comment by oscerd** [comment]
@rohanKanojia I didn't know you're working on the model upgrade, no problem. Lets wait for your upgrade :-)

**Comment by ibuziuk** [comment]
@rohanKanojia @oscerd  any news about `4.1.1` release plans ? not pushing for release, just wondering when it is planned ;-) ?

**Comment by rohanKanojia** [comment]
@ibuziuk : ah, I apologize for the delay in release. Somehow review of #1269 got delayed :-( . I'm gonna make a release in a week or two.

**Comment by ibuziuk** [comment]
@rohanKanojia thanks for an update ;-) will be keeping an eye on it to update https://github.com/eclipse/che/issues/11981

**Comment by rohanKanojia** [comment]
@ibuziuk : Kubernetes-client 4.1.1 has been released. Sorry for the delay ;-)
