### PR TITLE
fix #4519: correcting how the config refreshes

### LINKED ISSUE #4519: TokenRefreshInterceptor doesn't respect kubernetes.disable.autoConfig flag
### Describe the bug

TokenRefreshInterceptor doesn't respect kubernetes.disable.autoConfig flag.

### Fabric8 Kubernetes Client version

6.2.0

### Steps to reproduce

Instantiate client using
```java
KubernetesClientBuilder().withConfig(Config.fromKubeconfig(someconfig)).build();
```
but also have a file at `/var/run/secrets/kubernetes.io/serviceaccount/token` with some different token than in `someconfig`.
After 1 minute my calls start failing with `"Unauthorized! Token may have expired! Please log-in again."`.

### Expected behavior

Calls don't start failing.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
## Description
fix for #4519 - refining how the config refreshes

It seems like a good idea also to always apply the system/env properties after loading the kubeconfig - https://github.com/fabric8io/kubernetes-client/compare/master...shawkins:refresh_config?expand=1#diff-7506ddc44edef04cb34dcde13c56d00ed3b1d35d848ded8f1924ed44c03db953R608

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java [hunk 1]
```diff
@@ -1432,4 +1460,12 @@ public void setAdditionalProperty(String name, Object value) {
     this.additionalProperties.put(name, value);
   }
 
+  public void setFile(File file) {
+    this.file = file;
+  }
+
+  public void setAutoConfigure(boolean autoConfigure) {
+    this.autoConfigure = autoConfigure;
+  }
```
Comment (manusa) [inline kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java:1469]: Why are the setters needed?

**Comment by manusa** [comment]
I'm not sure you linked the correct issue number (at least I don't see their relation)

**Comment by shawkins** [comment]
> I'm not sure you linked the correct issue number (at least I don't see their relation)

Sorry transposed the issue numbers.  Corrected now.

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java (hunk 1 above)
Comment (shawkins) [reply kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java:1469]: So that they will get set when we clone via the builder.  We create modified configs in special circumstances, in particular with the withRequestConfig calls.

Comment (manusa) [reply kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java:1469]: From the generated `io.fabric8.kubernetes.client.ConfigBuilder`:
```java
  public Config build() {
    Config buildable = new Config(fluent.getMasterUrl(),fluent.getApiVersion(),fluent.getNamespace(),fluent.isTrustCerts(),fluent.isDisableHostnameVerification(),fluent.getCaCertFile(),fluent.getCaCertData(),fluent.getClientCertFile(),fluent.getClientCertData(),fluent.getClientKeyFile(),fluent.getClientKeyData(),fluent.getClientKeyAlgo(),fluent.getClientKeyPassphrase(),fluent.getUsername(),fluent.getPassword(),fluent.getOauthToken(),fluent.getWatchReconnectInterval(),fluent.getWatchReconnectLimit(),fluent.getConnectionTimeout(),fluent.getRequestTimeout(),fluent.getRollingTimeout(),fluent.getScaleTimeout(),fluent.getLoggingInterval(),fluent.getMaxConcurrentRequests(),fluent.getMaxConcurrentRequestsPerHost(),fluent.isHttp2Disable(),fluent.getHttpProxy(),fluent.getHttpsProxy(),fluent.getNoProxy(),fluent.getErrorMessages(),fluent.getUserAgent(),fluent.getTlsVersions(),fluent.getWebsocketTimeout(),fluent.getWebsocketPingInterval(),fluent.getProxyUsername(),fluent.getProxyPassword(),fluent.getTrustStoreFile(),fluent.getTrustStorePassphrase(),fluent.getKeyStoreFile(),fluent.getKeyStorePassphrase(),fluent.getImpersonateUsername(),fluent.getImpersonateGroups(),fluent.getImpersonateExtras(),fluent.getOauthTokenProvider(),fluent.getCustomHeaders(),fluent.getRequestRetryBackoffLimit(),fluent.getRequestRetryBackoffInterval(),fluent.getUploadConnectionTimeout(),fluent.getUploadRequestTimeout());
    buildable.setDefaultNamespace(fluent.isDefaultNamespace());
    buildable.setAuthProvider(fluent.getAuthProvider());
    buildable.setContexts(fluent.getContexts());
    buildable.setCurrentContext(fluent.getCurrentContext());
    buildable.setAutoConfigure(fluent.isAutoConfigure());
    buildable.setFile(fluent.getFile());
    return buildable;
  }
```

**Review by manusa — APPROVED** [review]
