### PR TITLE
fix: simple enums are now supported when generating CRDs

### LINKED ISSUE #2819: CRD generation fails when walking the type hierarchy for enums
The issue is that java describes enums as generic types of `java.lang.Enum` which causes a mismatch between the number of arguments and the type definition in `Types.applyTypeArguments`, causing an `IndexOutOfBoundsException`.

### PR DESCRIPTION
**Pull request by metacosm**
`Types.applyTypeArguments` doesn't crash when encountering differing
cardinality between type definition and actual arguments, which was the
case when encountering an enum property. Such properties are now
generated by enumerating their cases name and recording them in the
validation schema. Not sure if that actually covers all cases.

Fixes #2819.

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

File: crd-generator/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java [hunk 1]
```diff
@@ -183,7 +185,18 @@ public T internalFrom(TypeRef typeRef) {
         if (typeRef instanceof ClassRef) { // Handle complex types
           ClassRef classRef = (ClassRef) typeRef;
           TypeDef def = classRef.getDefinition();
-          return internalFrom(def);
+
+          // check if we're dealing with an enum
+          if(def.isEnum()) {
+            final JsonNode[] enumValues = def.getProperties().stream()
+              .map(Property::getName)
+              .map(JsonNodeFactory.instance::textNode)
```
Comment (iocanel) [inline crd-generator/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java:193]: It seems really weird to me that we have to use Jacson from within our mapping mechanism.
Then again this is how our `JsonSchemaProps` class is structured and we can't do much about it. At least not while we are trying to deal with the enum issue.

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by manusa** [comment]
Hi @metacosm 
Could you add a/some unit test/s to verify your fix please?

**Review by manusa — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]
