### PR TITLE
fix(port-forwarding): Service Port-Forwarding Ignores Service Port Mapping

### LINKED ISSUE #7372: Service Port-Forwarding Ignores Service Port Mapping
### Describe the bug

**Summary:**
Service-based port forwarding fails when the service port differs from the target port, because Fabric8 attempts to connect to the service port inside the pod's network namespace instead of the target port specified in the service definition.

**Expected Behavior:**
When using `service.portForward(servicePort, localPort)`, Fabric8 should connect to the service's `targetPort` inside the pod, similar to how `kubectl port-forward service/name` works.

**Actual Behavior:**
Fabric8 attempts to connect to the `servicePort` inside the pod's network namespace, ignoring the service's port mapping to `targetPort`.

**Service Configuration:**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-webapp
  namespace: my-namespace
spec:
  ports:
  - name: http
    port: 80          # Service port
    targetPort: 8080  # Pod port where application actually listens
  selector:
    app: my-webapp
```

**Reproduction Code:**
```java
// This fails - tries to connect to pod's port 80 instead of 8080
LocalPortForward servicePortForward = client.services()
    .inNamespace("my-namespace")
    .withName("my-webapp") 
    .portForward(80, 8080);
```

**Comparison with kubectl:**
```bash
# This works correctly - kubectl properly maps service port 80 to target port 8080
kubectl port-forward service/my-webapp 8080:80 -n my-namespace
```

**Root Cause:**
The service port-forwarding implementation appears to use the service port (80) when establishing the connection inside the pod's network namespace, but should use the service's `targetPort` (8080) instead.

**Workaround:**
Use pod-based port forwarding instead of service-based port forwarding:
```java
Pod targetPod = client.pods()
    .inNamespace("my-namespace")
    .withLabel("app", "my-webapp")
    .list().getItems().get(0);
    
LocalPortForward portForward = client.pods()
    .inNamespace("my-namespace") 
    .withName(targetPod.getMetadata().getName())
    .portForward(8080, 8080);
```

### Fabric8 Kubernetes Client version

7.4.0

### Steps to reproduce

**Service Configuration:**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-webapp
  namespace: my-namespace
spec:
  ports:
  - name: http
    port: 80          # Service port
    targetPort: 8080  # Pod port where application actually listens
  selector:
    app: my-webapp
```

**Reproduction Code:**
```java
// This fails - tries to connect to pod's port 80 instead of 8080, but does not throw any exceptions and reports that the portForward is alive
LocalPortForward servicePortForward = client.services()
    .inNamespace("my-namespace")
    .withName("my-webapp") 
    .portForward(80, "127.0.0.1", 8080);
```

### Expected behavior

When using `service.portForward(servicePort, localPort)`, Fabric8 should connect to the service's `targetPort` inside the pod, similar to how `kubectl port-forward service/name` works.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

macOS

### Fabric8 Kubernetes Client Logs

```shell
io.fabric8.kubernetes.client.KubernetesClientException: Received an error from the remote socket 
error forwarding port 80 to pod [pod-id], uid : failed to execute portforward in network namespace 
"/var/run/netns/cni-[namespace-id]": failed to connect to localhost:80 inside namespace "[pod-id]", 
IPv4: dial tcp4 127.0.0.1:80: connect: connection refused 
IPv6 dial tcp6 [::1]:80: connect: connection refused
```

### Additional context

**Environment:**
- Java version: Corretto-21.0.8.9.1
- Kubernetes version: v1.34.1+k3s1

### PR DESCRIPTION
**Pull request by ash-thakur-rh**
## Description
Fixes #7372 

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by ash-thakur-rh** [comment]
WIP! Need to add more tests and add more robust assertions.

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceOperationsImpl.java [hunk 1]
```diff
@@ -131,38 +130,50 @@ private Pod matchingPod() {
...
-        .portForward(port, localInetAddress, localPort);
+        .portForward(getTargetPortAsInt(s, port), localInetAddress, localPort);
+  }
+
+  private int getTargetPortAsInt(Service service, int port) {
+    return service.getSpec().getPorts().stream()
+        .filter(p -> p.getPort().equals(port))
+        .map(p -> p.getTargetPort().getIntVal())
+        .findFirst()
+        .orElse(port);
```
Comment (manusa) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceOperationsImpl.java]: Consider adding a null filter to handle named target ports gracefully:

```java
private int getTargetPortAsInt(Service service, int port) {
  return service.getSpec().getPorts().stream()
      .filter(p -> p.getPort().equals(port))
      .map(p -> p.getTargetPort().getIntVal())
      .filter(Objects::nonNull)  // Handle named ports gracefully
      .findFirst()
      .orElse(port);
}
```

If `targetPort` is a named port (String like `"http"`), `getIntVal()` returns `null`. Without this filter, the code would throw a `NullPointerException` when unboxing to `int`.

With this change, named ports would fall back to the original port (same as "port not found"), which is consistent and avoids the NPE. Full support for named ports could be addressed in a separate enhancement.

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceOperationsImpl.java [hunk 2]
```diff
@@ -131,38 +130,50 @@ private Pod matchingPod() {
...
+        .portForward(getTargetPortAsInt(s, port), in, out);
   }
 
   @Override
   public LocalPortForward portForward(int port, int localPort) {
-    Pod m = matchingPod();
+    Service s = requireFromServer();
+    Pod m = matchingPod(s);
     return new PodOperationsImpl(context.getClient())
         .inNamespace(m.getMetadata().getNamespace())
```
Comment (manusa) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceOperationsImpl.java]: Consider chaining the `LocalPortForward` overloads like `PodOperationsImpl` does, to reduce code duplication:

```java
@Override
public LocalPortForward portForward(int port) {
  return portForward(port, 0);
}

@Override
public LocalPortForward portForward(int port, int localPort) {
  return portForward(port, null, localPort);
}

@Override
public LocalPortForward portForward(int port, InetAddress localInetAddress, int localPort) {
  Service s = requireFromServer();
  Pod m = matchingPod(s);
  return new PodOperationsImpl(context.getClient())
      .inNamespace(m.getMetadata().getNamespace())
      .withName(m.getMetadata().getName())
      .portForward(getTargetPortAsInt(s, port), localInetAddress, localPort);
}
```

This way only the most complete overload contains the actual logic, and the simpler ones just delegate. The `PortForward portForward(int port, ReadableByteChannel in, WritableByteChannel out)` method would still need its own implementation since it returns a different type.
