### PR TITLE
fix #3149 #3127 - deprecate updateStatus(item) operation and use resourceVersion if available

### LINKED ISSUE #3127: deprecate updateStatus(item) operation
Similar to updateStatus, should be a simple update(item) method available as well?

cc @rohanKanojia

### LINKED ISSUE #3149: replace(item) should use the resourceVersion from the item if possible
When not specifically locked on a version, replace(item) should see if the item has a resourceVersion set before retrieving the latest.  If the replace fails, it can then get the latest on the next retry.

### PR DESCRIPTION
**Pull request by shawkins**
## Description
This fix deprecates updateStatus now that there are other operations.  It also consolidates more util calls, makes some of the messages more consistent, and uses the passed in resourceVersion first in a replace operation.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

File: kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedClusterScopeCustomResourceApiTest.java [hunk 1]
```diff
@@ -139,9 +140,28 @@ void testStatusUpdate() throws InterruptedException {
...
+
+    @Test
+    void testStatusReplace() throws InterruptedException {
+      Star updatedStar = getStar();
+      StarStatus starStatus = new StarStatus();
+      starStatus.setLocation("M");
+      updatedStar.setStatus(starStatus);
+
+      server.expect().put().withPath("/apis/example.crd.com/v1alpha1/stars/sun/status").andReturn(200, updatedStar).once();
+      server.expect().get().withPath("/apis/example.crd.com/v1alpha1/stars/sun").andReturn(200, "{\"apiVersion\":\"example.crd.com/v1alpha1\",\"kind\":\"Star\",\"metadata\":{\"name\":\"sun\",\"resourceVersion\":\"1\"},\"spec\":{\"type\":\"G\",\"location\":\"Galaxy\"},\"status\":{\"location\":\"M\"}}").once();
```
Comment (iocanel) [inline kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedClusterScopeCustomResourceApiTest.java:156]: Why do you use an `Star` in the first expectation and a `String` in the later?

Comment (shawkins) [reply kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedClusterScopeCustomResourceApiTest.java:156]: I've updated to just use strings and be more readable.

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java [hunk 2]
```diff
@@ -83,13 +85,13 @@ public T edit(Visitor... visitors) {
...
   protected Gettable<T> fromServer(ObjectMeta metadata) {
-    if (getName() != null) {
+    if (Utils.isNotNullOrEmpty(getName())) {
       return fromServer();
     }
     if (metadata != null) {
       return withName(metadata.getName()).fromServer();
     }
-    throw new KubernetesClientException("Name not specified. But operation requires name.");
+    throw new KubernetesClientException("resourceVersion not specified for an operation requiring one.");
```
Comment (manusa) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java:94]: `resourceVersion`? shouldn't it be name?

**Comment by shawkins** [comment]
https://github.com/fabric8io/kubernetes-client/pull/3136/checks?check_run_id=2611315593#step:6:1160 - is a timing issue with the patch(item) call.  If the item is modified before the patch, it can be invalid and return a 422.  There used to be retry logic for patch, but it was based upon replace, so it was looking for a 409.  I would vote to leave the current patch logic and not add a retry.  This test could be changed to use replace.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by shawkins** [comment]
rebased and added changelog entries

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
We have this CHEATSHEET doc which contains various examples of usages of client. It might have gotten a bit outdated due to recent changes in client. Shall we update it for `updateStatus` deprecation and add some examples of `patchStatus`, `replaceStatus` etc?

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/StatusUpdatable.java [hunk 3]
```diff
@@ -23,6 +23,7 @@
    *
    * @param item kubernetes object
    * @return updated object
+   * @deprecated please use one of patchStatus, editStatus, or replaceStatus
    */
   T updateStatus(T item);
```
[the remark this answers is not in the document]
Comment (shawkins) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/StatusUpdatable.java:29]: added now

**Comment by shawkins** [comment]
okay, updated the cheatsheet as well.

**Review by manusa — APPROVED** [review]

**Comment by shawkins** [comment]
> Could you please review?

Should be fully rebased now.
