### PR TITLE
Fix CRD generation

### LINKED ISSUE #2910: Move crd-generator tests out of kubernetes-itests
The tests/folder in https://github.com/fabric8io/kubernetes-client/tree/master/kubernetes-itests/src/test/java/io/fabric8/crd is not an "integration test", it doesn't need a connection to an active kubernetes cluster, so it should not belong to the `kubernetes-itests` module.

As this is more a "unit test" like, probably it should be inside the same `crd-generator-apt` module, or at best in the module `kubernetes-test` module.

Just as a side note, this test is not running on CI, since the e2e-tests workflow filter the tests that are from `-Dtest="io.fabric8.[kubernetes|openshift].**"` not the io.fabric8.crd.

/cc @metacosm

### PR DESCRIPTION
**Pull request by metacosm**
## Description
In the process of fixing tests after they moved out, we realized tha

1. these tests were not running
2. the CRD generation was not properly working:
    - status sub-resource was not properly generated from APT
    - schema generation was broken from API
    
Fixes #2910 
Supersedes #2969 

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by metacosm** [comment]
Note that this requires a new sundrio release.

File: crd-generator/api/src/main/java/io/fabric8/crd/generator/CustomResourceInfo.java [hunk 1]
```diff
@@ -121,43 +121,29 @@ public TypeDef definition() {
...
-
       final TypeDef definition = ClassTo.TYPEDEF.apply(customResource);
-      
-      // walk the type hierarchy until we reach CustomResource or a ParameterizedType
-      Type genericSuperclass = customResource.getGenericSuperclass();
-      String typeName = genericSuperclass.getTypeName();
-      while (!TYPE_NAME.equals(typeName) && !(genericSuperclass instanceof ParameterizedType)) {
-        genericSuperclass = ((Class) genericSuperclass).getGenericSuperclass();
-        typeName = genericSuperclass.getTypeName();
+      if (DESCRIBE_TYPE_DEFS) {
```
Comment (manusa) [inline crd-generator/api/src/main/java/io/fabric8/crd/generator/CustomResourceInfo.java:131]: I'm not following the logic here (this will never be true). Is this flag supposed to be something that will be removed in the future?

Comment (metacosm) [reply crd-generator/api/src/main/java/io/fabric8/crd/generator/CustomResourceInfo.java:131]: This is a flag to activate the type description. The idea is that you need to recompile so that it can be optimized away by the compiler when not active.

Comment (manusa) [reply crd-generator/api/src/main/java/io/fabric8/crd/generator/CustomResourceInfo.java:131]: Yes, but how is the flag activated, it's a `false` constant

Comment (metacosm) [reply crd-generator/api/src/main/java/io/fabric8/crd/generator/CustomResourceInfo.java:131]: You recompile the code to activate it :)
Being a constant means that if the constant is false, the compiler will (presumably) remove the code during compilation.

Comment (manusa) [reply crd-generator/api/src/main/java/io/fabric8/crd/generator/CustomResourceInfo.java:131]: 🤯 OK, I still don't understand how this class being part of a provided API would ever be recompiled, but I trust you know what you're doing.

**Review by manusa — APPROVED** [review]
LGTM, thx

**Review by rohanKanojia — APPROVED** [review]
