### PR TITLE
Fix #1013 : Kubernetes connection is not getting closed.

### LINKED ISSUE #1013: Kubernetes Connection is not closed.
When running tests using OpenShift/Kubernetes the following warning is thrown:
```
WARNING: A connection to https://api.starter-us-east-2.openshift.com/ was leaked. 
Did you forget to close a response body? To see where this was allocated, 
set the OkHttpClient logger level to 
FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```
On setting the level to FINE, the logs shows this coming from [WatchConnectionManager.java#L145](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java#L145).

```
Feb 15, 2018 10:52:18 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://192.168.42.69:8443/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
    at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:143)
    at okhttp3.RealCall.captureCallStackTrace(RealCall.java:78)
    at okhttp3.RealCall.enqueue(RealCall.java:87)
    at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:180)
    at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:427)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.internal.WatchConnectionManager.runWatch(WatchConnectionManager.java:145)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.internal.WatchConnectionManager.<init>(WatchConnectionManager.java:97)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.base.BaseOperation.watch(BaseOperation.java:701)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.base.BaseOperation.watch(BaseOperation.java:689)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.base.HasMetadataOperation.periodicWatchUntilReady(HasMetadataOperation.java:200)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.base.HasMetadataOperation.waitUntilReady(HasMetadataOperation.java:227)
    at io.fabric8.openshift.clnt.v3_1.handlers.DeploymentConfigHandler.waitUntilReady(DeploymentConfigHandler.java:78)
    at io.fabric8.openshift.clnt.v3_1.handlers.DeploymentConfigHandler.waitUntilReady(DeploymentConfigHandler.java:33)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl$1.run(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:105)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
Just want to ensure if this is because of some missing call in cube to close the client or if it is something related to f8-client.

### PR DESCRIPTION
**Pull request by rohanKanojia**
#1013  Using clonedClient seems to be creating connection leaks(as seen in
OkHttp's platform logs when using client). Therefore create a new client
instead of cloning it from previous one.

### CODE REVIEW

**Comment by oscerd** [comment]
ok to test

**Comment by piyush1594** [comment]
Please add CHANGELOG.md @rohanKanojia

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java [hunk 1]
```diff
@@ -82,7 +84,9 @@ public WatchConnectionManager(final OkHttpClient client, final BaseOperation<T,
     this.reconnectLimit = reconnectLimit;
     this.websocketTimeout = websocketTimeout;
 
-    this.clonedClient = client.newBuilder().readTimeout(this.websocketTimeout, TimeUnit.MILLISECONDS).build();
+    Config aConfig = baseOperation.getConfig();
+    aConfig.setRequestTimeout((int)this.websocketTimeout);
+    this.clonedClient = HttpClientUtils.createHttpClient(baseOperation.getConfig());
```
Comment (lordofthejars) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java]: Now it is not cloned anymore. I will use other name like `client`

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java [hunk 2]
```diff
@@ -82,7 +84,9 @@ public WatchConnectionManager(final OkHttpClient client, final BaseOperation<T,
     this.reconnectLimit = reconnectLimit;
     this.websocketTimeout = websocketTimeout;
 
-    this.clonedClient = client.newBuilder().readTimeout(this.websocketTimeout, TimeUnit.MILLISECONDS).build();
+    Config aConfig = baseOperation.getConfig();
```
Comment (lordofthejars) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java]: Why not call it `kubernetesClientConfig` at the end it is what it is right?

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java [hunk 3]
```diff
@@ -20,11 +20,13 @@
...
 import io.fabric8.kubernetes.api.model.WatchEvent;
+import io.fabric8.kubernetes.client.Config;
 import io.fabric8.kubernetes.client.KubernetesClientException;
 import io.fabric8.kubernetes.client.Watch;
 import io.fabric8.kubernetes.client.Watcher;
 import io.fabric8.kubernetes.client.dsl.base.BaseOperation;
 import io.fabric8.kubernetes.client.dsl.base.OperationSupport;
+import io.fabric8.kubernetes.client.utils.HttpClientUtils;
 import io.fabric8.kubernetes.client.utils.Utils;
 import okhttp3.*;
```
Comment (lordofthejars) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java]: I know it is not coming from this PR but are we ok with using star operator?

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java (hunk 1 above)
Comment (iocanel) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java]: I don't like the idea of mutating the configuration object (it possilby mutates the global config instance of the client). I would prefer creating a new instance of the configuration object. Something like:

    Config requestConfig = new ConfigBuilder(baseOperation.getConfig()).withReadtTimeout(....).build();

An other option worth exploring (not sure if applicable here). is to use the withRequestConfig() thing that we have and allows you to execute a single request with a custom configuration object. As I said it might not be applicable here. So no need to put too much effort in this.

In a perfect world none of our object should have setters. Who knows maybe in 4.x....

**Comment by piyush1594** [comment]
@iocanel Can you please take a look once more?

**Comment by piyush1594** [comment]
Let's merge this.

**Comment by piyush1594** [comment]
[merge]

**Comment by mrsiano** [comment]
Is this PR already part of 3.1.10 ?

**Comment by oscerd** [comment]
No. Look at the changelog.

https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md
