### PR TITLE
fix (kubernetes-client-api) : `Config`'s `autoConfigure` should disable auto configuration

### LINKED ISSUE #6137: ConfigBuilder.withAutoConfigure is not working
### Describe the bug

I create a kube config in code with `ConfigBuilder`, and I don't want to load the default kube config file, so I use the `withAutoConfig` method of the `ConfigBuilder`  to set the autoConfig to false, but it's not working, the default kube config file still loaded.

after inverstigate, I found the default constructor of the `ConfigBuilder` will create a new `Config`
```java
  public ConfigBuilder() {
    this(new Config());
  }
```
below is the default constructor of the `Config`, It will get the autoConfig value from system properties or env, not from the configBuilder

```java
@Deprecated
  public Config() {
    this(!disableAutoConfig());
  }

  private static boolean disableAutoConfig() {
    return Utils.getSystemPropertyOrEnvVar(KUBERNETES_DISABLE_AUTO_CONFIG_SYSTEM_PROPERTY, false);
  }
```

### Fabric8 Kubernetes Client version

6.12.1

### Steps to reproduce

1. make sure the default kubeConfig file exist and have some cluster configurations
2. create a config with `ConfigBuilder`, set the autoConfig to false
3. check the config object, it have configurations from the default kubeConfig file

### Expected behavior

no default kubeConfig file loaded if autoConfig is false

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.23

### Environment

Windows

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fix #6137 

`Config`'s autoConfigure field should behave as per expectations.

We need to make changes to ConfigBuilder and ConfigFluent in order to achieve this.
- Add a new Constructor with additional boolean arguments `autoConfigure` and   `shouldSetDefaultValues`
- Add a new package private class `SundrioConfig` that would extend `Config` for generating the Sundrio Builder for Config
- Move generated classes `ConfigBuilder` and `ConfigFluent` to `src/main/java`
   - `ConfigBuilder` would extend generated SundrioConfigBuilder and override the `build()` method by calling `disableAutoConfig()` if `autoConfigure` is not provided by the user. Earlier `ConfigBuidler` was calling `new Config()` (this was enabling auto configuration)
- Make all fields in Config and ResourceConfig classes use boxed types instead of primitive types so that we can distinguish whether user has configured them.

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by manusa — COMMENTED** [review]
Let's review this together after the stand-up, I'm not sure how these changes deal with the issue

**Review by manusa — COMMENTED** [review]
Could you please create an initial PR with the tests so that it's clear that the changes in the constructor are not affecting the previous behavior.

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java [hunk 1]
```diff
@@ -350,56 +366,256 @@ public Config(String masterUrl, String apiVersion, String namespace, boolean tru
...
+      int requestTimeout,
+      long scaleTimeout, int loggingInterval, int maxConcurrentRequests, int maxConcurrentRequestsPerHost,
+      boolean http2Disable, String httpProxy, String httpsProxy, String[] noProxy,
+      String userAgent, TlsVersion[] tlsVersions, long websocketPingInterval, String proxyUsername,
+      String proxyPassword, String trustStoreFile, String trustStorePassphrase, String keyStoreFile, String keyStorePassphrase,
+      String impersonateUsername, String[] impersonateGroups, Map<String, List<String>> impersonateExtras,
+      OAuthTokenProvider oauthTokenProvider, Map<String, String> customHeaders, int requestRetryBackoffLimit,
+      int requestRetryBackoffInterval, int uploadRequestTimeout, boolean onlyHttpWatches, NamedContext currentContext,
+      List<NamedContext> contexts, boolean autoConfigure) {
+    autoConfigure(this, null);
```
Comment (manusa) [inline kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java:393]: This looks weird. Why is autoconfigure always invoked? It wasn't before (in some of the methods)

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java [hunk 2]
```diff
@@ -350,56 +366,256 @@ public Config(String masterUrl, String apiVersion, String namespace, boolean tru
...
+    if (!autoConfigure) {
+      this.apiVersion = Objects.equals(this.apiVersion, apiVersion) ? "v1" : apiVersion;
+      this.namespace = Objects.equals(this.namespace, namespace) ? null : namespace;
```
Comment (manusa) [inline kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java:396]: these also look weird?
why is the variable overridden to an arbitrary (magic) value in case the current and provided values match?

**Review by manusa — APPROVED** [review]
LGTM, thx!
