### PR TITLE
fix #4668: use acme.cert-manager.io ApiGroup for Orders and Challenges

### LINKED ISSUE #4688: extension: cert-manager acme-resources Order / Challenge using wrong value in @Group Annotation
### Describe the bug

Following cert-manager acme classes are using the wrong k8s api group: `cert-manager.io` instead of `acme.cert-manager.io`
* [Order](https://github.com/fabric8io/kubernetes-client/blob/master/extensions/certmanager/model-v1/src/generated/java/io/fabric8/certmanager/api/model/acme/v1/Order.java#L73)
* [Challenge](https://github.com/fabric8io/kubernetes-client/blob/master/extensions/certmanager/model-v1/src/generated/java/io/fabric8/certmanager/api/model/acme/v1/Challenge.java#L73)

This leads to empty results using `Order` or `Challenge` using current cert-manager extension.

Using kubectl requesting those resources with api-version `cert-manager.io` throws errors:
* `kubectl get orders.v1.cert-manager.io`
* `kubectl get challenges.v1.cert-manager.io`

Using kubectl requesting those resources with api-version `acme.cert-manager.io` works:
* `kubectl get orders.v1.acme.cert-manager.io`
* `kubectl get challenges.v1.acme.cert-manager.io`

### Fabric8 Kubernetes Client version

6.3.1

### Steps to reproduce

Running this java code throws in both cases exceptions
```java
            OrderList orders = certManagerClient.v1().orders().list();
            if(orders.getItems().isEmpty()) {
                throw new IllegalStateException("No orders found!");
            }
```

```java

            ChallengeList challenges = certManagerClient.v1().challenges().list();
            if(challenges.getItems().isEmpty()) {
                throw new IllegalStateException("No challenges found!");
            }
```

### Expected behavior

Using the correct value in `@Group`-annotation with `acme.cert-manager.io` for `Order` and `Challenge` returns existing resources

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by grafjo**
## Description

Fix #4688 

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: extensions/certmanager/generator-v1/cmd/generate/generate.go [hunk 1]
```diff
@@ -58,7 +58,7 @@ func main() {
 	// optional ApiGroup and ApiVersion for the go package (which is added to the generated java class)
 	packageMapping := map[string]schemagen.PackageInformation{
 		"github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1": {JavaPackage: "io.fabric8.certmanager.api.model.v1", ApiGroup: "cert-manager.io", ApiVersion: "v1"},
-		"github.com/cert-manager/cert-manager/pkg/apis/acme/v1":        {JavaPackage: "io.fabric8.certmanager.api.model.acme.v1", ApiGroup: "cert-manager.io", ApiVersion: "v1"},
+		"github.com/cert-manager/cert-manager/pkg/apis/acme/v1":        {JavaPackage: "io.fabric8.certmanager.api.model.acme.v1", ApiGroup: "acme.cert-manager.io", ApiVersion: "v1"},
 		"github.com/cert-manager/cert-manager/pkg/apis/meta/v1":        {JavaPackage: "io.fabric8.certmanager.api.model.meta.v1", ApiGroup: "cert-manager.io", ApiVersion: "v1"},
```
Comment (shawkins) [inline extensions/certmanager/generator-v1/cmd/generate/generate.go:62]: Should this be changed as well? https://github.com/cert-manager/cert-manager/blob/ee8ec69fadff165afa96c2dd22264c16fdb7d065/pkg/apis/meta/doc.go#L22

The internal ones probably need updated as well, but they aren't contributing anything to our model correct?

Comment (rohanKanojia) [reply extensions/certmanager/generator-v1/cmd/generate/generate.go:62]: Umm, I didn't see any CRD in this apiGroup. All generated classes in this package don't seem to have any `@Group` annotation as well. We can add it for the sake of completeness

Comment (rohanKanojia) [reply extensions/certmanager/generator-v1/cmd/generate/generate.go:62]: Maybe we can do this in a separate issue.

File: extensions/certmanager/tests/src/test/java/io/fabric8/certmanager/test/model/V1ChallengeTest.java [hunk 2]
```diff
@@ -0,0 +1,40 @@
+/**
+ * Copyright (C) 2022 Red Hat, Inc.
+ * <p>
+ * Licensed under the Apache License, Version 2.0 (the "License");
+ * you may not use this file except in compliance with the License.
+ * You may obtain a copy of the License at
+ * <p>
+ * http://www.apache.org/licenses/LICENSE-2.0
+ * <p>
```
[the remark this answers is not in the document]
Comment (grafjo) [reply extensions/certmanager/tests/src/test/java/io/fabric8/certmanager/test/model/V1ChallengeTest.java:9]: I'll fix it with that mvn goal - thx

File: extensions/certmanager/tests/src/test/java/io/fabric8/certmanager/test/model/V1ChallengeTest.java [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+  void testChallengeModelApiVersion() {
+
+    Challenge challenge = new ChallengeBuilder()
+      .withNewMetadata().withName("my-challenge").endMetadata()
+      .build();
+
+    assertNotNull(challenge);
+    assertEquals("my-challenge", challenge.getMetadata().getName());
+    assertEquals("acme.cert-manager.io/v1", challenge.getApiVersion());
+  }
```
[the remark this answers is not in the document]
Comment (grafjo) [reply extensions/certmanager/tests/src/test/java/io/fabric8/certmanager/test/model/V1ChallengeTest.java:38]: I prefere to use `model-v1` because it's a simple unit-test, will update the PR

File: extensions/certmanager/generator-v1/cmd/generate/generate.go (hunk 1 above)
Comment (grafjo) [reply extensions/certmanager/generator-v1/cmd/generate/generate.go:62]: @shawkins about the meta-package I don't know if we need an update.

@rohanKanojia where is the `@Group` annotation missing? I can add that as well.

**Review by rohanKanojia — APPROVED** [review]

**Comment by grafjo** [comment]
@rohanKanojia fixed the formatting issues

**Review by manusa — APPROVED** [review]
