### PR TITLE
Fix #2802: Kubernetes Mock Server Crud Mode should reject invalid Kubernetes resources

### LINKED ISSUE #2802: NPE in HasMetadataOperation patch and replace
While testing logic that patches a secret, HasMetadataOperation encounters a NullPointerException if the resource exists but has no metadata on [line 120](https://github.com/fabric8io/kubernetes-client/blob/b015fb957047956d3656c3043e4c663957e82de9/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L120). There is a null check, however the operation is not performed within that null check, and an ObjectMeta is not created/set in response to the resource having no metadata.

It appears that [replace](https://github.com/fabric8io/kubernetes-client/blob/b015fb957047956d3656c3043e4c663957e82de9/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L74) would also suffer from the same issue.

I am testing using the [mock KubernetesServer](https://github.com/fabric8io/kubernetes-client/blob/b015fb957047956d3656c3043e4c663957e82de9/kubernetes-client/src/test/java/io/fabric8/kubernetes/server/mock/KubernetesServer.java) and understand that this scenario is not likely to occur when running against a live Kubernetes server instance. This may also be an issue in KubernetesServer, as the secret is created with metadata. I am using [createOrReplace(Secret)](https://github.com/fabric8io/kubernetes-client/blob/b015fb957047956d3656c3043e4c663957e82de9/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/CreateOrReplaceable.java#L27) to write the initial secret in my test with the basic pseudocode below:

```java
Secret secret = new SecretBuilder()
  .editOrNewMetadata()
    .withNamespace(namespace)
    .withName(name)
  .endMetadata()
  .addToData("key.json", value)
  .build();

kubeClient
  .secrets()
  .inNamespace(namespace)
  .createOrReplace(secret);
```

The code being tested is patching with this pseudocode:
```java
Secret secret = new SecretBuilder()
  .addToData("key.json", updatedValue)
  .build();

  kubeClient
    .secrets()
    .inNamespace(namespace)
    .withName(name)
    .patch(secret);
```

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #2802 

Right now when a resource with no metadata is created, instead of throwing KubernetesClientException, we're throwing a
NullPointerException here:
  KubernetesAttributesExtractor.extractMetadataAttributes:L154

KubernetesMockServer should validate whether object sent in the request body contains metadata or not

Note that this doesn't solve your issue when you're using
KubernetesMockServer in expectations mode since you set what you'll be
getting as response to be received by yourself

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

File: kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java [hunk 1]
```diff
@@ -316,4 +327,63 @@ private int doCreate(String path, String s, String event) {
...
+  }
+
+  private boolean isResourceValid(HasMetadata item) {
+    if (item == null) {
+      return false;
+    }
+    if (item.getMetadata() == null) {
+      return false;
+    }
+    return item.getMetadata().getName() != null || item.getMetadata().getGenerateName() != null;
```
Comment (manusa) [inline kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java:387]: Utils.isNotNullOrEmpty

File: kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java [hunk 2]
```diff
@@ -316,4 +327,63 @@ private int doCreate(String path, String s, String event) {
...
+  private StatusCause getFailureStatusCause(HasMetadata h) {
+    StatusCauseBuilder statusCauseBuilder = new StatusCauseBuilder();
+    if (h == null) {
+      statusCauseBuilder.withField(".")
+        .withMessage("Nothing provided")
+        .withReason("ValueRequired");
+    } else if (h.getMetadata() == null ||
+      (h.getMetadata().getName() == null && h.getMetadata().getGenerateName() == null)) {
+      statusCauseBuilder.withField(".metadata.name")
+        .withMessage("Required value: name or generateName is required")
```
Comment (manusa) [inline kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java:374]: This is not OK.

isResourceValid should throw a checked Exceptionwith the given message (what happens if we add more validations in the future?).

The method `validateRequestBodyAndHandleRequest` should call `isResourceValid` or better renamed to `validateResource`. Whenever that method throws an exception, the failed body is returned with the message provided by that Exception.

Not sure if my description is clear enough. If not, we can discuss in a call.

**Review by manusa — APPROVED** [review]
LGTM, thx!
