### PR TITLE
fix(crd-generator): Fail if multiple versions are marked as stored

### LINKED ISSUE #5845: CRDGenerator allows setting multiple custom resource versions as stored
### Describe the bug

The CRDGenerator does not detect that multiple schema versions are marked as stored if two or more versions are provided. This is not allowed for a CRD.

The CRDGenerator already includes a check to detect this, but it is not working because the check is executed too early in the decorator chain.

### Fabric8 Kubernetes Client version

6.11.0

### Steps to reproduce

Run this test:
https://github.com/fabric8io/kubernetes-client/blob/0c80a66d10bf7096864246ce453413e0da4edbd2/crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java#L190

### Expected behavior

The test should fail but does not because both versions of the "Multiple" example are marked as stored:
https://github.com/fabric8io/kubernetes-client/tree/0c80a66d10bf7096864246ce453413e0da4edbd2/crd-generator/api/src/test/java/io/fabric8/crd/example/multiple

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by baloo42**
## Description

Fixes a bug where the CRDGenerator allows generating CRDs with multiple versions marked as stored. 

Additional changes:
- Extract some assertions to a seperate class (reusing is planned in the next PRs)
- Allow debugging decorator sequence by changing the log level to trace
  (refer to [simplelogger.properties](https://github.com/fabric8io/kubernetes-client/blob/main/crd-generator/api/src/test/resources/simplelogger.properties#L22) during test runs)

Fixes #5845 

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java [hunk 1]
```diff
@@ -578,32 +575,6 @@ void checkK8sValidationRules() throws Exception {
     assertTrue(outputDir.delete());
   }
 
-  private void assertFileEquals(final File expectedFile, final File actualFile) {
```
Comment (andreaTP) [inline crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java:581]: Since we are at it, would it make sense use approval tests?
We are using them in the `java-generator`.

File: crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/EnsureSingleStorageVersionDecorator.java [hunk 2]
```diff
@@ -19,46 +19,39 @@
...
 
   @Override
   public void andThenVisit(CustomResourceDefinitionSpecFluent<?> spec, ObjectMeta resourceMeta) {
-    Predicate<CustomResourceDefinitionVersionBuilder> hasStorageVersion = v -> v.getStorage() != null && v.getStorage();
+    List<CustomResourceDefinitionVersion> versions = spec.buildVersions();
 
-    if (spec.hasVersions() && !spec.hasMatchingVersion(hasStorageVersion)) {
-      spec.editFirstVersion().withStorage(true).endVersion();
-    }
+    List<String> storageVersions = versions.stream()
```
Comment (andreaTP) [inline crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/EnsureSingleStorageVersionDecorator.java:38]: I recall that, at some point, someone unrolled the `stream`s into plain loops because of [this feature](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CRD-generator.md#generate-crds-in-parallel) and I believe that we are not testing it quite enough.

As ugly as it may sound 😞 , have you tried those changes with that flag enabled?

**Review by andreaTP — APPROVED** [review]
Added a couple of notes, but they can be tackled in follow up PRs IMHO.

Would be great to have a quick review from @metacosm here, or maybe @csviri is interested too ...

File: crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java (hunk 1 above)
Comment (baloo42) [reply crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java:581]: I'm not sure if I understand you correct. What do you mean with "approval tests"?

My general intention is to reduce the size of the CRDGeneratorTest to make it easier to write more tests.

To make this happen, I started with extracting some assertion methods to the utility class `CRDGeneratorAssertions`.

Then I added `CRDGeneratorExamplesTest` to group all "end to end" tests.
We can add here a test for each of our examples in the future.

This `CRDGeneratorExamplesTest` class is also extended by `ParallelCRDGeneratorExamplesTest` , so that every test written in `CRDGeneratorExamplesTest` is also tested with the "parallel generation" feature.


I have looked into the java-generator tests and found `io.fabric8.java.generator.testing.KubernetesResourceDiff`. I was not aware of it but if I look a little bit closer at it now, it reads YAML files to an internal representation and compares this. In conclusion `KubernetesResourceDiff` can compare the syntax of a two yaml files but it cannot ensure that both YAML files are exactly the same (which is important for the deterministic output feature).

Comment (andreaTP) [reply crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java:581]: Approval tests are "Golden Master", if I understand it correctly you are comparing plain `yaml` to files stored in git, and that's the use-case for them.

Dependency:
https://github.com/fabric8io/kubernetes-client/blob/0c80a66d10bf7096864246ce453413e0da4edbd2/java-generator/core/pom.xml#L95

Approval tests:
https://github.com/fabric8io/kubernetes-client/blob/main/java-generator/core/src/test/java/io/fabric8/java/generator/ApprovalTest.java

and here you find the "golden masters":
https://github.com/fabric8io/kubernetes-client/tree/main/java-generator/core/src/test/resources/io/fabric8/java/generator/approvals

I think that using a similar infrastructure in the `crd-generator` might help in your noble goal of:

> reduce the size of the CRDGeneratorTest to make it easier to write more tests

File: crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/EnsureSingleStorageVersionDecorator.java (hunk 2 above)
Comment (baloo42) [reply crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/EnsureSingleStorageVersionDecorator.java:38]: Yes, that's why I added `ParallelCRDGeneratorExamplesTest`. It should work for parallel generation, too.

You are also right it's not the nicest way, but it's also hard to improve the situation here.
The core problem is not that we are working e.g. with streams or a predicate or a atomic reference. (That's just optimization of the error output).

The real problem is that the decorator sort algorithm is not working as expected on "multi level after/before" dependencies.

That's why I changed...

```java
@Override
public Class<? extends Decorator>[] after() {
  return new Class[] { AddCustomResourceDefinitionResourceDecorator.class,
      AddCustomResourceDefinitionVersionDecorator.class, SetStorageVersionDecorator.class };
}
```
<details><summary>Toggle me to see Decorator order...</summary>

```
[main] TRACE io.fabric8.crd.generator.v1.decorator.AddCustomResourceDefinitionResourceDecorator [apiGroup=sample.fabric8.io, kind=Multiple, name=multiples.sample.fabric8.io, plural=multiples, scope=Cluster]
[main] TRACE io.fabric8.crd.generator.v1.decorator.AddCustomResourceDefinitionResourceDecorator [apiGroup=sample.fabric8.io, kind=Multiple, name=multiples.sample.fabric8.io, plural=multiples, scope=Cluster]
[main] TRACE io.fabric8.crd.generator.v1.decorator.AddCustomResourceDefinitionVersionDecorator [name:multiples.sample.fabric8.io, version:v1]
[main] TRACE io.fabric8.crd.generator.v1.decorator.AddCustomResourceDefinitionVersionDecorator [name:multiples.sample.fabric8.io, version:v2]
[main] TRACE io.fabric8.crd.generator.v1.decorator.AddSchemaToCustomResourceDefinitionVersionDecorator [name:multiples.sample.fabric8.io, version:v1]
[main] TRACE io.fabric8.crd.generator.v1.decorator.AddSchemaToCustomResourceDefinitionVersionDecorator [name:multiples.sample.fabric8.io, version:v2]
[main] TRACE io.fabric8.crd.generator.v1.decorator.EnsureSingleStorageVersionDecorator [name:multiples.sample.fabric8.io]
[main] TRACE io.fabric8.crd.generator.v1.decorator.EnsureSingleStorageVersionDecorator [name:multiples.sample.fabric8.io]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SetDeprecatedVersionDecorator [name:multiples.sample.fabric8.io, version:v1, deprecated:false, deprecationWarning:null]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SetDeprecatedVersionDecorator [name:multiples.sample.fabric8.io, version:v2, deprecated:false, deprecationWarning:null]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SetServedVersionDecorator [name:multiples.sample.fabric8.io, version:v1, served:true]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SetServedVersionDecorator [name:multiples.sample.fabric8.io, version:v2, served:true]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SetStorageVersionDecorator [name:multiples.sample.fabric8.io, version:v1, storage:false]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SetStorageVersionDecorator [name:multiples.sample.fabric8.io, version:v2, storage:true]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SortCustomResourceDefinitionVersionDecorator [name:multiples.sample.fabric8.io]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SortCustomResourceDefinitionVersionDecorator [name:multiples.sample.fabric8.io]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SortPrinterColumnsDecorator [name:multiples.sample.fabric8.io, version:v2]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SortPrinterColumnsDecorator [name:multiples.sample.fabric8.io, version:v1]
```
</details>

to
```java
@Override
public Class<? extends Decorator>[] after() {
  return new Class[] {
      CustomResourceDefinitionVersionDecorator.class
  };
}
```
<details><summary>Toggle me to see Decorator order...</summary>

```
[main] TRACE io.fabric8.crd.generator.v1.decorator.AddCustomResourceDefinitionResourceDecorator [apiGroup=sample.fabric8.io, kind=Multiple, name=multiples.sample.fabric8.io, plural=multiples, scope=Cluster]
[main] TRACE io.fabric8.crd.generator.v1.decorator.AddCustomResourceDefinitionResourceDecorator [apiGroup=sample.fabric8.io, kind=Multiple, name=multiples.sample.fabric8.io, plural=multiples, scope=Cluster]
[main] TRACE io.fabric8.crd.generator.v1.decorator.AddCustomResourceDefinitionVersionDecorator [name:multiples.sample.fabric8.io, version:v1]
[main] TRACE io.fabric8.crd.generator.v1.decorator.AddCustomResourceDefinitionVersionDecorator [name:multiples.sample.fabric8.io, version:v2]
[main] TRACE io.fabric8.crd.generator.v1.decorator.AddSchemaToCustomResourceDefinitionVersionDecorator [name:multiples.sample.fabric8.io, version:v1]
[main] TRACE io.fabric8.crd.generator.v1.decorator.AddSchemaToCustomResourceDefinitionVersionDecorator [name:multiples.sample.fabric8.io, version:v2]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SetDeprecatedVersionDecorator [name:multiples.sample.fabric8.io, version:v1, deprecated:false, deprecationWarning:null]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SetDeprecatedVersionDecorator [name:multiples.sample.fabric8.io, version:v2, deprecated:false, deprecationWarning:null]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SetServedVersionDecorator [name:multiples.sample.fabric8.io, version:v1, served:true]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SetServedVersionDecorator [name:multiples.sample.fabric8.io, version:v2, served:true]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SetStorageVersionDecorator [name:multiples.sample.fabric8.io, version:v1, storage:false]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SetStorageVersionDecorator [name:multiples.sample.fabric8.io, version:v2, storage:true]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SortPrinterColumnsDecorator [name:multiples.sample.fabric8.io, version:v2]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SortPrinterColumnsDecorator [name:multiples.sample.fabric8.io, version:v1]
[main] TRACE io.fabric8.crd.generator.v1.decorator.EnsureSingleStorageVersionDecorator [name:multiples.sample.fabric8.io]
[main] TRACE io.fabric8.crd.generator.v1.decorator.EnsureSingleStorageVersionDecorator [name:multiples.sample.fabric8.io]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SortCustomResourceDefinitionVersionDecorator [name:multiples.sample.fabric8.io]
[main] TRACE io.fabric8.crd.generator.v1.decorator.SortCustomResourceDefinitionVersionDecorator [name:multiples.sample.fabric8.io]
```
</details>

The `EnsureSingleStorageVersionDecorator` extends `CustomResourceDefinitionDecorator` and because of that it is working on the `CustomResourceDefinition` "level". Meanwhile the `CustomResourceDefinitionVersionDecorator` and `SetStorageVersionDecorator` extend `CustomResourceDefinitionVersionDecorator`, which means that they are working on the CustomResourceDefinitionVersion "level". 

So far as I understand the sorting algorithm of the decorators mixing of multiple levels is not supported.

Maybe we should improve this sorting algorithm (or document the behaviour)?
Or am I wrong?

File: crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java (hunk 1 above)
Comment (baloo42) [reply crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java:581]: Thanks for the hints. I didn't know the project [ApprovalTests](https://github.com/approvals/ApprovalTests.Java) and yes it looks like it can replace the current self-developed assertions.

https://github.com/fabric8io/kubernetes-client/issues/5850

Comment (andreaTP) [reply crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java:581]: Nice!
Thanks a lot for taking the time to make the improvement 👍 let's discuss approvals in the other PR.

File: crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/EnsureSingleStorageVersionDecorator.java (hunk 2 above)
Comment (andreaTP) [reply crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/EnsureSingleStorageVersionDecorator.java:38]: > Yes, that's why I added `ParallelCRDGeneratorExamplesTest`. It should work for parallel generation, too.

That's nice, but I'm afraid that the execution of the annotation processors in the tests is not the same as when triggered using the "real" annotation processor.
Probably, the only way to fully test is to spin a new module like this:
https://github.com/fabric8io/kubernetes-client/tree/main/crd-generator/test
but enabling parallelism.

Thanks a lot for the rest of the analysis, I agree with this:

> Maybe we should improve this sorting algorithm (or document the behaviour)?

I see that someone had already been through this trouble: https://github.com/fabric8io/kubernetes-client/blob/0c80a66d10bf7096864246ce453413e0da4edbd2/crd-generator/api/src/main/java/io/fabric8/crd/generator/Resources.java#L84-L90

Hopefully, we can get another pair of eyes from @metacosm or @iocanel here.

Comment (andreaTP) [reply crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/EnsureSingleStorageVersionDecorator.java:38]: > can we implement this in a seperate PR

that's fine for me

**Review by rohanKanojia — APPROVED** [review]

**Comment by andreaTP** [comment]
Probably this fixes #5507 as well

**Review by metacosm — APPROVED** [review]

**Comment by metacosm** [comment]
Thank you for your improvements and fixes. These are much appreciated!

File: crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/EnsureSingleStorageVersionDecorator.java [hunk 3]
```diff
@@ -19,46 +19,39 @@
...
+        .filter(v -> Optional.ofNullable(v.getStorage()).orElse(true))
```
[the remark this answers is not in the document]
Comment (baloo42) [reply crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/EnsureSingleStorageVersionDecorator.java:39]: For endusers, it's already documented in the annotation itself:
https://github.com/fabric8io/kubernetes-client/blob/main/kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/annotation/Version.java#L46

```java
/**
   * Whether this version corresponds to the persisted version for the associated CRD. Note that only one version can set
   * {@code storage} to {@code true} for a given CRD.
   *
   * @return {@code true} if this version corresponds to the persisted version for the associated CRD, {@code false} otherwise
   */
  boolean storage() default true; // <-- here
```


For (internal) CRDGenerator developers:
If a property like `storage` is equal to the default value, it is usually set to null in the internal representation.
This allows to omit the property during the schema generation, so that only those properties end up in the schema for which the value is not equal to the schema default.

We could start with a `DEVELOPMENT.md` file in the CRDGenerator package to document such internal behaviours. (There are a few more things which should be documented e.g. the sorting algorithm for the decorators...)

[the remark this answers is not in the document]
Comment (metacosm) [reply crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/EnsureSingleStorageVersionDecorator.java:39]: > For endusers, it's already documented in the annotation itself: https://github.com/fabric8io/kubernetes-client/blob/main/kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/annotation/Version.java#L46
> 
> ```java
> /**
>    * Whether this version corresponds to the persisted version for the associated CRD. Note that only one version can set
>    * {@code storage} to {@code true} for a given CRD.
>    *
>    * @return {@code true} if this version corresponds to the persisted version for the associated CRD, {@code false} otherwise
>    */
>   boolean storage() default true; // <-- here
> ```

Right, I missed that. This might be good enough.

**Review by manusa — APPROVED** [review]
LGTM, thx!
