### PR TITLE
Issue-2804: Swap assertion arguments so they are in the correct order (expected value, actual value)

### LINKED ISSUE #2804: Fix assertions in SerializationTest#unmarshalCRDWithSchema
We have these assertions in `SerializationTest` right now:
https://github.com/fabric8io/kubernetes-client/blob/b015fb957047956d3656c3043e4c663957e82de9/kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java#L60-L70

If you look closely, assertion arguments in `assertEquals` are not passed in the wrong order. Sonar reports this as a code smell[0] and it's happening at other places too , Would be awesome if someone interested in contributing could fix this issue. We just need to swap arguments so that the expected value is first and the actual value is second. You can check this for more information[1]

[0] https://sonarcloud.io/organizations/fabric8io/issues?projects=fabric8io_kubernetes-client&resolved=false&rules=java%3AS3415
[1] https://sonarcloud.io/organizations/fabric8io/rules?open=java%3AS3415&rule_key=java%3AS3415

### PR DESCRIPTION
**Pull request by amitdaga**
Fix #2804 

## Description

- Swap assertion arguments so they are in the correct order (expected value, actual value)
- Minor: Imports reorganized in few classes
- Minor: Anonymous new Visitor() replaced with lambda 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/KubernetesListTest.java [hunk 1]
```diff
@@ -15,35 +15,33 @@
...
 import static org.junit.jupiter.api.Assertions.assertNotNull;
 import static org.junit.jupiter.api.Assertions.assertNull;
 
+import org.hamcrest.CoreMatchers;
+import org.junit.jupiter.api.Test;
+
 public class KubernetesListTest {
 
     @Test
-    public void testDefaultValues() throws JsonProcessingException {
```
Comment (amitdaga) [inline kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/KubernetesListTest.java:31]: This exception is never thrown.

**Review by oscerd — APPROVED** [review]

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
a test is failing:
```
Error:  Errors: 
Error:    KubernetesListTest.testVisitor:88 » IndexOutOfBounds Index: 1, Size: 1
[INFO] 
Error:  Tests run: 35, Failures: 0, Errors: 1, Skipped: 0
```
