### PR TITLE
fix #4496: removing list handling from watching

### LINKED ISSUE #4496: KubernetesResourceList resources are not handled properly by AbstractWatchManager
### Describe the bug

In #4365 was introduced [change](https://github.com/fabric8io/kubernetes-client/pull/4365/files?diff=unified&w=1#diff-7ca5806d751b9d76ce33e1adbef2dabd2ef3c10d499aeb66215451bd8bbff802L285-R295) that in a nutshell changed from this:
```
if (object instanceof KubernetesResourceList) {}
else if (object instanceof HasMetadata) {}
```
to 
```
if (object instanceof HasMetadata) {
  if (object instanceof KubernetesResourceList) {}
}
```

But AFAIU KubernetesResourceList doesn't implement HasMetadata so any event will end up with error `io.fabric8.kubernetes.client.WatcherException: Invalid object received: ...`

### Fabric8 Kubernetes Client version

5.12.4

### Steps to reproduce

1. Send event with any List resource to watcher
2. Got an exception

### Expected behavior

List resources expected to be handled

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
## Description
fix #4496 removing list handling from the abstract watch manager.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java [hunk 1]
```diff
@@ -250,33 +248,9 @@ private WatchEvent contextAwareWatchEventDeserializer(String messageSource)
...
-    // so lets try parse the message as a KubernetesResource
-    // as it will probably be a list of resources like a BuildList
-    if (object == null) {
-      object = Serialization.unmarshal(messageSource, KubernetesResource.class);
-      if (event == null) {
-        event = new WatchEvent(object, "MODIFIED");
-      } else {
-        event.setObject(object);
-      }
-    }
```
Comment (manusa) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java:270]: What happens if you watch API Groups in a real cluster?

From yesterday discussion, the assumption was that receiving a list as an event was not possible, but the former comment here says otherwise.

**Review by oscerd — APPROVED** [review]

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java (hunk 1 above)
Comment (shawkins) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java:270]: > What happens if you watch API Groups in a real cluster?

I couldn't quite determine what that comment meant.  You cannot watch APIGroup directly, and we have no example, including Builds, where a watch returns a list rather than a WatchEvent.  My only guess is that this was from early behavior in OpenShift and the comment could be referencing not using oapi for the watch.

Comment (manusa) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java:270]: OK, I recall now you did provide that explanation.

**Review by manusa — APPROVED** [review]
LGTM, thx!
