### PR TITLE
fix #3255 adding basic resourceVersion handling

### LINKED ISSUE #3255: KubernetesServer in CRUD mode does not handle resourceVersion properly
I'm currently writing an Operator, and have the following logic on my event handler to prevent doing pointless reconciliation when there are no changes.

```java
  @Override
  public void onUpdate(ConfigMap oldConfigMap, ConfigMap newConfigMap) {
    if (oldConfigMap.getMetadata().getResourceVersion().equals(newConfigMap.getMetadata().getResourceVersion())) {
      LOGGER.info("Skipping UPDATE for ConfigMap ({}), nothing changed...", newConfigMap.getMetadata().getName());
      return;
    }

    enqueue(newConfigMap);
  }
```

However when writing my tests with KubernetesServer in CRUD mode this does not work as the server never increments the resourceVersion on updates - it is always "1".

### PR DESCRIPTION
**Pull request by shawkins**
## Description
Adding basic resourceVersion handling for #3255 - does not add list/watch querying based upon resourceVersion..

fix #3255

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by manusa — APPROVED** [review]

File: kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CrudTest.java [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+import io.fabric8.kubernetes.client.dsl.NonNamespaceOperation;
+import io.fabric8.kubernetes.client.dsl.PodResource;
+import io.fabric8.kubernetes.client.server.mock.EnableKubernetesMockClient;
+import io.fabric8.kubernetes.client.server.mock.KubernetesMockServer;
+import org.junit.jupiter.api.Test;
+
+import static org.junit.jupiter.api.Assertions.assertEquals;
+
+@EnableKubernetesMockClient(crud = true)
+class CrudTest {
```
Comment (rohanKanojia) [inline kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CrudTest.java:33]: Just a minor nitpick, Could the test class name be a bit more descriptive?

Comment (shawkins) [reply kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CrudTest.java:33]: Most of the other tests were specific to a resource, I want a test class that is generic to any crud operation rather than resource type.  How about CrudMetadataTest?

Comment (rohanKanojia) [reply kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CrudTest.java:33]: Sounds, good. I'd just keep CrudTest suffix just to match with other crud tests e.g. MetadataCrudTest, ResourceMetadataCrudTest

**Review by rohanKanojia — APPROVED** [review]
