### PR TITLE
Several informer related changes

### LINKED ISSUE #3968: The Store API is not writable
### Describe the bug

I am updating the kubernetes client in my application from 5.4.1 to the latest 5.12.1. And the API changed, I cannot write in the store of the informer anymore. The workaround I have is to explicietly cast the Store instance into a Cache, to be able to use the add function.
My use case is that we have an external database where is stored all the history of the statuses of the pods launched by Argo. To be sure that we don't miss any status update, we use the informer pattern. And in case of error where our application is not up, but pods are deleted during that time, before starting the informer we prepopulate the cache with the last known list of running pods. This way, at startup we get notified of any missed deletion. This pattern was found described in this exemple in the go client:
https://github.com/kubernetes/client-go/blob/2f52a105e63e9ac7affb1a0f533c62883611ba81/examples/workqueue/main.go#L202

Looking at the history of the fabric8 client, I see that the APIs have been removed by #3091

### Fabric8 Kubernetes Client version

other (please specify in additional context)

### Steps to reproduce

Use the Store API.

### Expected behavior

A writable Store API, like the go client has.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.21.6

### Environment

other (please specify in additional context)

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

_No response_

### LINKED ISSUE #3969: onUpdate is called on re-list even if resourceVersion is unchaged
### Describe the bug

When a re-list happens, an onUpdate event is received even if the object resourceVersion didn't change.
5.10.1

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

create a test having a relist to a quite short version
wait for the relist to happen
see that an onUpdate is triggered for even a not changed object

### Expected behavior

the onUpdate should not be triggered if resourceVersion is unchanged

### Runtime

OpenShift

### Kubernetes API Server version

1.22.3@latest

### Environment

Amazon

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
## Description
This addresses a host of informer related requests:

Fix #3969 - stop emitting sync events on relist - it was simplest to make this change to support #3968
Fix #3968 - added SharedInformer.initialState to set

Also took the parts of #3943 that were most general purpose, such as being able to add/remove indexers at any time, along with deprecating Informable.withIndexers

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/CacheImpl.java [hunk 1]
```diff
@@ -111,10 +97,27 @@ public synchronized T put(T obj) {
...
+    }
     this.updateIndices(oldObj, obj, key);
     return oldObj;
   }
 
+  static <T extends HasMetadata> int compareResourceVersions(T oldObj, T obj) {
+    if (oldObj == null) {
+      return -1;
+    }
+    return Long.compare(Long.parseLong(oldObj.getMetadata().getResourceVersion()),
```
Comment (hibnico) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/CacheImpl.java:117]: Even if I have never seen anything other than increasing numbers as resource versions, I think this is making too much assumption regarding the specification.
As declared in the official API, the resourceVersion is `an opaque value that represents the internal version of this object`, cf https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#objectmeta-v1-meta
As far as I can tell, the only thing we can do to tell if two versions are different, not order them.

Comment (shawkins) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/CacheImpl.java:117]: I agree that it's not inline with the official docs, but this is how resourceVersion will function until etcd is no longer being utilized.  You can see similar logic in the go client https://github.com/kubernetes/client-go/blame/45fb834fedea5c753501ea8ea597e2dc54080510/tools/cache/mutation_cache.go#L242

Obviously for your usage, you don't need this checking - if modifications are restricted to before the informer is running there's no consistency issue.  However I've been asked by the operator sdk team about also supporting proactive updates to the cache as well - and I really can't come up with any other to do that consistently.  My hope was to just address both of those cases together and providing a writable store in general.

The options are:
1. Offer an option to, or just allow, unsafe updates - I don't believe that's a good approach though
2. Restrict this checking to only when someone has made mutations after calling run and document that it may not always be supported
3. Only support modifications before run and still don't try to support consistent modifications after run has been called.

One more thing that I would need to add is that if this checking is done, is that relist needs to force updates.  In cases like this https://github.com/kubernetes/kubernetes/issues/107457 the restart of the api server will cause a relist and we'll see older resourceVersions - this is obviously an edge case which currently does't work even with the go client informers that are relisting with a resourceVersion.

Comment (shawkins) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/CacheImpl.java:117]: I'll update this to number 2 and also correct the update/delete to be atomic and then we can see what everyone thinks of that.

Comment (hibnico) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/CacheImpl.java:117]: Ok, I didn't know that resource versions were number due to etcd, nice to know. I am just a user of Kubernetes, so I can only relay, but I have a heard that for scaling kubernetes some companies have setup other kind of storage like postgres. Considering the code in the go client you pointed, I guess that even with other storage they ensured that resources version are still incresing numbers.
My biggest worry was about `Long.parseLong` raising exception and crashing all that.
Thank you for sharing.

Comment (shawkins) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/CacheImpl.java:117]: Looking at the additional complexity of accounting for forcing updates on relist and cases like https://github.com/kubernetes/kubernetes/issues/107457 - I'm having second thoughts as it's still not possible to ensure that your consistent with the api server.  So I'll have to keep maintaining it's not a good idea to manipulate the store on a running informer.  I'll refine this pr to 3 instead.

Comment (shawkins) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/CacheImpl.java]: Linking to #https://github.com/fabric8io/kubernetes-client/pull/3943#issuecomment-1067962930 and resolving this comment.  If the operator sdk want to pursue this logic, it will need to do so with an adjunct cache.

**Review by manusa — APPROVED** [review]
