### PR TITLE
fix: (java-generator) Use timezone format compatible with Kubernetes

### LINKED ISSUE #7116: java-generator type=string format=date-time serializes with format that is not compatible with k8s
Serialization code created by java-generator for type=string with format=date-time uses a timezone which is not compatible with kubernetes.

Example error message:
```
status.startTime: Invalid value: "2025-05-30T23:04:44Zulu": startTime in body must be of type date-time
```

See also:
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

### PR DESCRIPTION
**Pull request by matteriben**
## Description

fix: (java-generator) Use timezone format compatible with Kubernetes
Fixes #7116

Example error message:
```
Invalid value: "2025-05-30T23:04:44Zulu": startTime in body must be of type date-time
```

See also:
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by andreaTP** [comment]
Sorry for being late at the party here, date time has been especially challenging when it comes to date-time, the original fix was done in #5384
I distinctly remember choosing different formats for writing(stricter) than for reading, and allowing more use cases reported on SO.

In this case, I'd be a bit on the fence accepting a PR without an exhaustive set of examples to cover the change.
cc. @manusa

File: java-generator/core/src/main/java/io/fabric8/java/generator/Config.java [hunk 1]
```diff
@@ -33,8 +33,8 @@ public class Config {
   public static final Map<String, String> DEFAULT_PACKAGE_OVERRIDES = new HashMap<>();
   public static final List<String> DEFAULT_FILES_SUFFIXES = Arrays.asList(".yaml", ".yml", ".json");
   // RFC 3339 - from: https://swagger.io/docs/specification/data-models/data-types/
-  public static final String DEFAULT_SER_DATETIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ssVV";
-  public static final String DEFAULT_DESER_DATETIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ss[XXX][VV]";
+  public static final String DEFAULT_SER_DATETIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ssXXX";
+  public static final String DEFAULT_DESER_DATETIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ssXXX";
```
Comment (andreaTP) [inline java-generator/core/src/main/java/io/fabric8/java/generator/Config.java:37]: @matteriben here you are effectively restricting the date-time formats accepted by the deserializer, any specific reason for doing it?

File: java-generator/core/src/main/java/io/fabric8/java/generator/Config.java [hunk 2]
```diff
@@ -33,8 +33,8 @@ public class Config {
   public static final Map<String, String> DEFAULT_PACKAGE_OVERRIDES = new HashMap<>();
   public static final List<String> DEFAULT_FILES_SUFFIXES = Arrays.asList(".yaml", ".yml", ".json");
   // RFC 3339 - from: https://swagger.io/docs/specification/data-models/data-types/
-  public static final String DEFAULT_SER_DATETIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ssVV";
-  public static final String DEFAULT_DESER_DATETIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ss[XXX][VV]";
+  public static final String DEFAULT_SER_DATETIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ssXXX";
```
Comment (andreaTP) [inline java-generator/core/src/main/java/io/fabric8/java/generator/Config.java:36]: the `VV` format should be "stricter" (emit a more stable output) than `XXX` across different Java/JDK versions IIRC.

**Comment by matteriben** [comment]
> Sorry for being late at the party here, date time has been especially challenging when it comes to date-time, the original fix was done in #5384 I distinctly remember choosing different formats for writing(stricter) than for reading, and allowing more use cases reported on SO.
> 
> In this case, I'd be a bit on the fence accepting a PR without an exhaustive set of examples to cover the change. cc. @manusa

@andreaTP I'm also sorry for the delayed response here, I agree with you that this could benefit from more exhaustive test coverage. In particular the output of the serializer should be considered valid by the kubernetes api server and the deserializer should be able to handle anything that the kubernetes api server considers valid.
