### PR TITLE
Fix #3015: Log InterruptedException in debug when it is a nominal terminating behavior

### LINKED ISSUE #3015: DefaultController#processLoop interrupt should not display stackTrace
When stopping an informer, the DefaultController#processLoop displays the interruption stacktrace.
This is annoying as it makes think that this is an unexpected behaviour.

It should be replaced by:
```
log.warn("DefaultController#processLoop got interrupted {}", t.getMessage());
```

### PR DESCRIPTION
**Pull request by hibnico**
## Description

Here is a review of the catch of the InterruptedException and their logs. I have done more than looking to the core code of the client. These suggestions are up for debate, and thus can be reverted in this PR.

So, every log about an nominal InterruptedException is now in debug, with the message of the exception but not the stack trace.

Special cases on some catch that I found:
* `BaseOperation#createOrReplace`: there used to be a `printStackTrace`. I tried to improve it by a log and propagate the status of the interrupted thread. But considering the case here, maybe there is more to do.
* `CreateOrReplaceHelper#createOrReplaceItem`: same considerations
* `CHEATSHEET.md`: I have found these weird piece of catch without the `try` keyword. I took the liberty to juste remove it. Javac will raise an error about the InterruptedException to handle, I see no need to do it explicitely here in the cheat sheet.
* the code exemples: to make things uniform, I made the logs at the warn level

A side note on `PortForwardEquivalent` example. I don't see how the `countDownLatch` is usefull there, `countDown` is never called on it.

Fix #3015 
## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by rohanKanojia — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Controller.java [hunk 1]
```diff
@@ -157,7 +157,7 @@ private void processLoop() throws Exception {
       try {
         this.queue.pop(this.processFunc);
       } catch (InterruptedException t) {
-        log.warn("DefaultController#processLoop got interrupted {}", t.getMessage(), t);
+        log.debug("DefaultController#processLoop got interrupted: {}", t.getMessage());
```
Comment (akram) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Controller.java:160]: Just a side note: In some tests that I ran, the `t.getMessage()` just returned `null` which is not very informative.

**Review by akram — APPROVED** [review]

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Controller.java (hunk 1 above)
Comment (hibnico) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Controller.java:160]: From experience I never saw something usefull as a message of an `InterruptedException`. I kept the message in the log to continue as much as possible the current behavior. And maybe some jvm implementations provide additionnal info ? I don't mind removing the message if required.

Comment (akram) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Controller.java:160]: Let's keep it, better that nothing.

**Review by manusa — APPROVED** [review]
LGTM, thx!
