### PR TITLE
fix: Binding operations can be instantiated

### LINKED ISSUE #2656: Always getting class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to class java.lang.Class
Always getting this exception with such code 

```
Binding binding = new BindingBuilder()
                    .withNewMetadata().withName(pod.getMetadata().getName()).endMetadata()
                    .withNewTarget().withKind("Node").withApiVersion("v1").withName(node.getMetadata().getName()).endTarget()
                    .build();
```

`kubernetesClient.bindings().inNamespace(pod.getMetadata().getNamespace()).create(binding);`

```
java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to class java.lang.Class (sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl and java.lang.Class are in module java.base of loader 'bootstrap')
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.BindingOperationsImpl.<init>(BindingOperationsImpl.java:42) ~[kubernetes-client-4.10.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.BindingOperationsImpl.<init>(BindingOperationsImpl.java:34) ~[kubernetes-client-4.10.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.BindingOperationsImpl.<init>(BindingOperationsImpl.java:30) ~[kubernetes-client-4.10.3.jar:na]
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.bindings(DefaultKubernetesClient.java:198) ~[kubernetes-client-4.10.3.jar:na]
```

### PR DESCRIPTION
**Pull request by manusa**
## Description
fix #2656: Binding operations can be instantiated

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] ~~I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly~~
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by manusa** [comment]
https://gist.github.com/manusa/dda58cb3629f5b73b802cf687fd33291

File: kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/BindingTest.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+class BindingTest {
+
+  @Rule
+  public KubernetesServer server = new KubernetesServer();
+
+  private KubernetesClient client;
+
+  @BeforeEach
+  void setUp() {
+    client = server.getClient().inNamespace("test");
```
Comment (rohanKanojia) [inline kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/BindingTest.java:41]: nit, I think namespace is set to `test` by default even when you use `server.getClient()`. Is this `inNamespace(..)` call required?

Comment (manusa) [reply kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/BindingTest.java:41]: Not needed at all. I took the test preparation boiler-plate from the PodTest suite and didn't even check this method.
:+1: Removing it.

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
[merge]
