### PR TITLE
Fix #2226: SharedIndexInformer for non-namespaced resources not working

### LINKED ISSUE #2226: SharedIndexInformer for non-namespaced resources not working
Hi,

I'am trying to register an informer for the Namespace resource to get notified as soon a new Namespace is created or an existing is updated. The created URL by the KubernetesClient looks like `https://openshift.localhost:8443/api/v1/namespaces/myproject/namespaces` which is wrong. 

Snippet which I use to create the informer:
```
    @Inject
    KubernetesClient client;
...
        SharedInformerFactory informerFactory = client.informers();
        SharedIndexInformer<Namespace> namespaceInformer = informerFactory.sharedIndexInformerFor(Namespace.class, NamespaceList.class, 10 * 60 * 1000);
```

Same issue occurs for `ClusterRoleBinding`.

I tried to provide a custom `OperationContext` with different parameters which was not working due to https://github.com/fabric8io/kubernetes-client/pull/2213.

Log output:
```
2020-05-14 08:08:50,503 WARN  [io.fab.kub.cli.inf.cac.Controller] (informer-controller-Namespace) Reflector list-watching job exiting because the thread-pool is shutting down: java.util.concurrent.RejectedExecutionException: Error while starting ReflectorRunnable watch
        at io.fabric8.kubernetes.client.informers.cache.Reflector.listAndWatch(Reflector.java:85)
        at io.fabric8.kubernetes.client.informers.cache.Controller.run(Controller.java:112)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.RejectedExecutionException: Error while doing ReflectorRunnable list
        at io.fabric8.kubernetes.client.informers.cache.Reflector.getList(Reflector.java:73)
        at io.fabric8.kubernetes.client.informers.cache.Reflector.reListAndSync(Reflector.java:94)
        at io.fabric8.kubernetes.client.informers.cache.Reflector.listAndWatch(Reflector.java:80)
        ... 2 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://openshift.localhost:8443/api/v1/namespaces/myproject/namespaces. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:412)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:151)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:621)
        at io.fabric8.kubernetes.client.informers.SharedInformerFactory$1.list(SharedInformerFactory.java:134)
        at io.fabric8.kubernetes.client.informers.SharedInformerFactory$1.list(SharedInformerFactory.java:127)
        at io.fabric8.kubernetes.client.informers.cache.Reflector.getList(Reflector.java:67)
        ... 4 more

```

Are there any ways to register an SharedInformer for non-namespaced resources?

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #2226 

We are using BaseOperation for all list/watch operations in SharedInformerFactory, but
we are not aware of whether the resource is namespaced or not. This PR modifies code in
BaseOperation to read it from the annotation inside class of Kubernetes resource.

### CODE REVIEW

**Comment by rohanKanojia** [comment]
retest this please

File: kubernetes-model/pkg/schemagen/generate.go [hunk 1]
```diff
@@ -30,29 +30,36 @@ type PackageDescriptor struct {
...
 
 type schemaGenerator struct {
-	types              map[reflect.Type]*JSONObjectDescriptor
-	typeNames          map[reflect.Type]string
-	customTypeNames    map[string]string
-	packages           map[string]PackageDescriptor
-	typeMap            map[reflect.Type]reflect.Type
+	types           map[reflect.Type]*JSONObjectDescriptor
+	typeNames       map[reflect.Type]string
+	customTypeNames map[string]string
```
Comment (dev-gaur) [inline kubernetes-model/pkg/schemagen/generate.go:35]: are you sure about the tab spacing here?

File: kubernetes-model/pkg/schemagen/generate.go [hunk 2]
```diff
@@ -30,29 +30,36 @@ type PackageDescriptor struct {
...
+	packages        map[string]PackageDescriptor
+	typeMap         map[reflect.Type]reflect.Type
 }
 
-func GenerateSchema(t reflect.Type, packages []PackageDescriptor, typeMap map[reflect.Type]reflect.Type, customTypeNames  map[string]string, moduleName string) (*JSONSchema, error) {
+type CrdScope int32
+
+const (
+	Namespaced CrdScope = 0
+	Cluster    CrdScope = 1
```
Comment (dev-gaur) [inline kubernetes-model/pkg/schemagen/generate.go:44]: I see that you're trying to create an enumeration here. I suggest using [iota](https://golang.org/ref/spec#Iota)

```suggestion
	Namespaced CrdScope = iota
	Cluster    CrdScope = iota
```

File: kubernetes-model/pkg/schemagen/generate.go [hunk 3]
```diff
@@ -541,3 +553,22 @@ func (g *schemaGenerator) addConstraints(objectName string, propName string, pro
...
+		"Node",
+		"PersistentVolume",
+		"PodSecurityPolicy",
+		"ClusterRoleBinding",
+		"ClusterRole",
+		"PriorityClass",
+		"StorageClass":
+		return Cluster
+	}
+	return Namespaced
```
Comment (dev-gaur) [inline kubernetes-model/pkg/schemagen/generate.go:573]:
```suggestion
	switch t.Name() {
	case "MutatingWebhookConfiguration",
		"ValidatingWebhookConfiguration",
		"CustomResourceDefinition",
		"ComponentStatus",
		"Namespace",
		"Node",
		"PersistentVolume",
		"PodSecurityPolicy",
		"ClusterRoleBinding",
		"ClusterRole",
		"PriorityClass",
		"StorageClass":
            return Cluster
	default:
	    return Namespaced    
	}
```

Comment (rohanKanojia) [reply kubernetes-model/pkg/schemagen/generate.go:573]: What's the benefit of this change?

File: kubernetes-model/pkg/schemagen/generate.go (hunk 1 above)
Comment (rohanKanojia) [reply kubernetes-model/pkg/schemagen/generate.go:35]: Umm, I'm not sure. I just used `go fmt kubernetes-model/pkg/schemagen/generate.go` for formatting. Do you think it can have some side effects?

**Comment by rohanKanojia** [comment]
Thanks a lot for taking time to review :+1: . I think I should add a test for Cluster scope Custom Resources like you suggested :heavy_plus_sign:

File: kubernetes-model/pkg/schemagen/generate.go (hunk 3 above)
Comment (rohanKanojia) [reply kubernetes-model/pkg/schemagen/generate.go:573]: I think you're right. Switch case without `default` is generally considered code smells. let me modify this too in the next update.

File: kubernetes-model/pkg/schemagen/generate.go (hunk 1 above)
Comment (dev-gaur) [reply kubernetes-model/pkg/schemagen/generate.go:35]: oh. If `go fmt` says so then its alright :)

**Comment by rohanKanojia** [comment]
[merge]

**Comment by rohanKanojia** [comment]
[merge]
