### PR TITLE
fix: adds filtering and switches to iterative traversal

### LINKED ISSUE #5584: CRD Generator -- Stack overflow when using EnumMap type in Spec
### Describe the bug

I'm seeing a stack overflow error in the CrdGenerator when defining a `java.util.EnumMap` as a private field. I believe the cause of this is due to the fact that the library is trying to introspect the `Class<T> keyType` private field that is contained within `EnumMap`. Within the `Class` type is a `ConcurrentHashMap` which has a bunch of circular references and that's where the generator gets into infinite recursion.

This effects multiple versions of the client.

I believe this is caused by part of the design of the CRD generator, where it introspects private fields as the means of generating schemas. The fields that should be added to the spec/status schemas are the ones that will be serialized by Jackson when sending a CR instance to the kube api. The default behavior in Jackson is to look at public, non-static, non-transient fields. This is also the behavior of the serializer that is contained within fabric8. Therefore, the CRD generator should follow the same visibility rules.

I don't think that `private`, `static`, or `transient` properties should be added to the schema, but rather the way schemas are generated should be inverted. First look at public, non-static, non-transient methods (getters) and then check to see if there's a matching private field to pull annotations from. I believe that is the behavior that is expected from jackson.

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

Add

```
public enum Foo { BAR }

private EnumMap<Foo, String> enumToStringMap;
```

to any Spec or Status. Add it to `io.fabric8.crd.example.map.ContainingMapsSpec` to create a testable reproduction of the issue.

### Expected behavior

1. Stack overflow does not occur
2. Schema generation follows visibility rules of Jackson ObjectMapper

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

Stack trace for overflow

```
[ERROR] Tests run: 14, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.603 s <<< FAILURE! -- in io.fabric8.crd.generator.ParallelCRDGeneratorTest
[ERROR] io.fabric8.crd.generator.ParallelCRDGeneratorTest.mapPropertyShouldHaveCorrectValueType -- Time elapsed: 2.369 s <<< ERROR!
java.lang.StackOverflowError
        at java.base/java.util.stream.AbstractPipeline.wrapSink(AbstractPipeline.java:522)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.sundr.builder.BaseFluent.build(BaseFluent.java:58)
        at io.sundr.model.ClassRefFluentImpl.getArguments(ClassRefFluentImpl.java:227)
        at io.sundr.model.ClassRefBuilder.build(ClassRefBuilder.java:57)
        at io.sundr.model.ClassRefBuilder.build(ClassRefBuilder.java:7)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.sundr.builder.BaseFluent.build(BaseFluent.java:58)
        at io.sundr.model.ClassRefFluentImpl.getArguments(ClassRefFluentImpl.java:227)
        at io.sundr.model.ClassRefBuilder.build(ClassRefBuilder.java:57)
        at io.sundr.model.ClassRefBuilder.build(ClassRefBuilder.java:7)
        at io.sundr.model.PropertyFluentImpl.getTypeRef(PropertyFluentImpl.java:259)
...
io.fabric8.crd.generator.visitor.AnnotatedPropertyPathDetector.visitPropertiesClasses(AnnotatedPropertyPathDetector.java:91)
        at io.fabric8.crd.generator.visitor.AnnotatedPropertyPathDetector.visit(AnnotatedPropertyPathDetector.java:76)
        at io.fabric8.crd.generator.visitor.AnnotatedPropertyPathDetector.visit(AnnotatedPropertyPathDetector.java:34)
        at io.sundr.builder.Visitor.visit(Visitor.java:30)
        at io.sundr.builder.VisitorWiretap.visit(VisitorWiretap.java:79)
        at io.sundr.builder.BaseFluent.accept(BaseFluent.java:110)
        at io.sundr.builder.BaseFluent.accept(BaseFluent.java:139)
        at io.sundr.builder.BaseFluent.accept(BaseFluent.java:75)
        at io.fabric8.crd.generator.visitor.AnnotatedPropertyPathDetector.visitPropertiesClasses(AnnotatedPropertyPathDetector.java:91)
        at io.fabric8.crd.generator.visitor.AnnotatedPropertyPathDetector.visit(AnnotatedPropertyPathDetector.java:76)
```

### PR DESCRIPTION
**Pull request by shawkins**
## Description

closes #5584

It doesn't seem like we need traversal below java. classes as we're only looking for our annotations.  Also we can switch to an iterative traversal, which should be less likely to blow out.

cc @andreaTP 

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by rohanKanojia — APPROVED** [review]

File: crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AnnotatedMultiPropertyPathDetector.java [hunk 1]
```diff
@@ -84,15 +83,20 @@ public void visit(TypeDefBuilder builder) {
       if (!parents.contains(p) && !excludePropertyProcessing(p)) {
         ClassRef classRef = (ClassRef) p.getTypeRef();
         TypeDef propertyType = Types.typeDefFrom(classRef);
-        if (!propertyType.isEnum()) {
+        if (!propertyType.isEnum() && !classRef.getPackageName().startsWith("java.")) {
```
Comment (andreaTP) [inline crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AnnotatedMultiPropertyPathDetector.java:86]: this should be marked as a breaking change, can you add a line to the Changelog?
I'm fine shipping this with 6.10 but it should not be backported to 6.9 imho

**Review by andreaTP — APPROVED** [review]
Thanks a lot for sorting this out @shawkins !
I'm happy with your implementation as it looks more robust than before.

File: crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AnnotatedMultiPropertyPathDetector.java (hunk 1 above)
Comment (shawkins) [reply crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AnnotatedMultiPropertyPathDetector.java:86]: Can you elaborate on why this would be breaking?  Do you expect users to create their own subclasses / instances that look for annotations that are built-in to java?

Comment (andreaTP) [reply crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AnnotatedMultiPropertyPathDetector.java:86]: I expect edge cases where people are relying on `protected` fields inherited from `java.` classes.
Am I missing something?

Comment (shawkins) [reply crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AnnotatedMultiPropertyPathDetector.java:86]: Can you provide an example?  As far as I can see once you reach a property typed as a java. class, there is no scenario where one of its child properties could contain a non-builtin annotation.  If for example you have extended a java class and added your own fields, that would be in your own class - not one from a java. package.  Are you thinking that some users may be modifying java. classes directly?

Comment (andreaTP) [reply crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AnnotatedMultiPropertyPathDetector.java:86]: no, your explanation is fair, thanks for providing this detail 👍

**Review by manusa — APPROVED** [review]
