### PR TITLE
Fixed LoadMultipleDocumentsFromFileExample

### LINKED ISSUE #1603: LoadMultipleDocumentsFromFileExample Can't be executed.
Exception in thread "main" java.lang.ClassCastException: io.fabric8.kubernetes.api.model.IntOrStringBuilder cannot be cast to io.fabric8.kubernetes.api.model.ObjectMetaBuilder
	at io.fabric8.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:118)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:109)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:11)
	at io.fabric8.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:115)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:109)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:11)
	at io.fabric8.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:115)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:109)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:11)
	at io.fabric8.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:115)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:109)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:11)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.acceptVisitors(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:293)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:281)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:64)
	at io.fabric8.kubernetes.examples.LoadMultipleDocumentsFromFileExample.main(LoadMultipleDocumentsFromFileExample.java:47)

### PR DESCRIPTION
**Pull request by kunal-kushwaha**
Fixes #1603
No exception in thread after removing the use of accept() method. 
It's only being used in 2 files (this one and LoadExample) and the multiple documents are loading with no issues without it.

### CODE REVIEW

File: kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LoadMultipleDocumentsFromFileExample.java [hunk 1]
```diff
@@ -35,21 +35,14 @@ public static void main(String[] args) throws InterruptedException {
...
+    Config config = new ConfigBuilder().withMasterUrl(master).build();
     KubernetesClient client = new DefaultKubernetesClient(config);
 
     List<HasMetadata> list = client.load(LoadMultipleDocumentsFromFileExample.class.getResourceAsStream("/multiple-document-template.yml")).get();
     System.out.println("Found in file:" + list.size() + " items.");
     for (HasMetadata meta : list) {
       System.out.println(display(meta));
     }
-
-    list = client.load(LoadMultipleDocumentsFromFileExample.class.getResourceAsStream("/multiple-document-template.yml")).accept((Visitor<ObjectMetaBuilder>) item -> item.addToLabels("visitorkey", "visitorvalue")).get();
```
Comment (rohanKanojia) [inline kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LoadMultipleDocumentsFromFileExample.java]: Umm, Thanks for fixing this. Did you get any chance to find out why this section of code was throwing an error? I think that can be done as a separate issue also.

Comment (pk044) [reply kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LoadMultipleDocumentsFromFileExample.java]: this line should not be deleted - it will work if you turn the lambda into an anonymous class instead. casting should be also avoided since its error-prone with this library

Comment (kunal-kushwaha) [reply kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LoadMultipleDocumentsFromFileExample.java]: @pk044 : Thanks for the feedback, it worked!
@rohanKanojia : It was due to lambda for some reason.

**Comment by rohanKanojia** [comment]
Thanks @pk044 @kunal-kushwaha

**Comment by rohanKanojia** [comment]
[merge]

**Comment by manusa** [comment]
Relates to #1369
