### PR TITLE
refinements and clarifications to the validation of names

### LINKED ISSUE #5220: KubernetesResourceUtil issues
The KubernetesResourceUtil methods related to resource names, labels, and annotations are not sufficiently documented or in some cases wrong.  Resources names may be up to 253 characters, not just 63.  Annotation and label keys name portion is limited to 63 chars, but they may contain a / separated prefix and with its own restrictions and the total character may be up to 253 characters long. 
 Annotation values are not restricted.

### PR DESCRIPTION
**Pull request by shawkins**
## Description
closes #5220

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [x] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java [hunk 1]
```diff
@@ -333,19 +350,56 @@ public static boolean isValidName(String name) {
...
-      }
-    }
-    return true;
+    return areLabelsValid(map);
+  }
+
+  /**
+   * Checks the given map keys and values for validity as labels.
+   */
+  public static boolean areLabelsValid(Map<String, String> map) {
```
Comment (rohanKanojia) [inline kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java:394]: javadoc seems to be missing `@param` and `@return`

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java [hunk 2]
```diff
@@ -333,19 +350,56 @@ public static boolean isValidName(String name) {
...
+    return map.entrySet().stream().allMatch(e -> isValidKey(e.getKey()) && isValidName(e.getValue()));
+  }
+
+  /**
+   * Checks the given map keys validity as annotations.
+   */
+  public static boolean areAnnotationsValid(Map<String, String> map) {
```
Comment (rohanKanojia) [inline kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java:401]: https://github.com/fabric8io/kubernetes-client/pull/5435/files#r1319927691

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java (hunk 1 above)
Comment (shawkins) [reply kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java:394]: I got a little lazy as they seemed self-explanitory.  I'll add something.

**Review by sunix — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]
