### PR TITLE
Fix createOrReplace for Loadables

### LINKED ISSUE #602: Ambiguity with BaseOperation createOrReplace()
[relevant code](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L352-L362)

```
  @Override
  public T createOrReplace(T item) {
    if (Utils.isNullOrEmpty(name) && item instanceof HasMetadata) {
      return withName(((HasMetadata)item).getMetadata().getName()).createOrReplace(item);
    }
    if (get() == null) {
      return create(item);
    } else {
      return replace(item);
    }
  }

```
For the case of first-time creation of a resource. The `get()` here constructs a url using `getNamespacedUrl` which results in something like: `http://<kube_master>/api/v1/<resource>`. This url usually returns a `<resource>List` and the condition `get() == null` is never true!

meaning that the replace workflow is invoked. which predictably fails at a PUT on the non-existent resource.

example usage (this will fail): `client.resourceQuotas().inNamespace(namespace).load(resourceQuotaInputStream).createOrReplace(resourceQuota);`

relevant PR: #538 
kubernetes-client version tested with: v1.4.16 (however, this code hasn't been updated in the subsequent releases)

am I understanding this wrong? or will the `createOrReplace()` workflow never behave as expected?

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #602

This adds more tests as well as sneaking in a change to allow no args `createOrReplace` following `load` to allow `client.load(is).createOrReplace()` which is currently not possible.

### CODE REVIEW

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java [hunk 1]
```diff
@@ -350,11 +350,22 @@ public T apply(T resource) {
...
+
+    if (item == null) {
+      throw new IllegalArgumentException("Nothing to create.");
+    }
+
     if (Utils.isNullOrEmpty(name) && item instanceof HasMetadata) {
       return withName(((HasMetadata)item).getMetadata().getName()).createOrReplace(item);
     }
-    if (get() == null) {
+    if (fromServer().get() == null) {
```
Comment (jimmidyson) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java]: This was the sneaky missing `fromServer` btw.

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java [hunk 2]
```diff
@@ -350,11 +350,22 @@ public T apply(T resource) {
   }
 
   @Override
-  public T createOrReplace(T item) {
+  public T createOrReplace(T... items) {
+    T item = getItem();
```
Comment (iocanel) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java]: why do you store getItems() to item, if you are going to do nothing with it and replace it a few lines below? This lines seems uneeded.

Comment (iocanel) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java]: Unless you want to support items.length == 0. Eitherway, its a bit confusing

**Comment by iocanel** [comment]
[merge]

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java (hunk 2 above)
Comment (jimmidyson) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java]: Yeah that is exactly why. This enables `client.pods().load(...).createOrReplace()` whereas before you'd have to pass something in to `createOrReplace`.
