### PR TITLE
Fix #2672: WaitUntilReady for Service resource throws IllegalArgumentException

### LINKED ISSUE #2672: Item needs to be one of [Node, Deployment, ReplicaSet, StatefulSet, Pod, DeploymentConfig, ReplicationController], but was: [Service]
We're watching service readiness using following code:
```java
final Service service = this.kubernetesClient
                        .services()
                        .inNamespace(namespace)
                        .withName(name)
                        .waitUntilReady(60, TimeUnit.SECONDS);
````
We used this code with version `4.6.0` and it worked.
After upgrading to version `4.13.0` it stopped working with the following exception:
```
java.lang.IllegalArgumentException: Item needs to be one of [Node, Deployment, ReplicaSet, StatefulSet, Pod, ReplicationController], but was: [Service]
	at io.fabric8.kubernetes.client.internal.readiness.Readiness.isReady(Readiness.java:62)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.lambda$waitUntilReady$6(BaseOperation.java:1109)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilConditionWithRetries(BaseOperation.java:1131)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilCondition(BaseOperation.java:1115)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilReady(BaseOperation.java:1109)
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.ServiceOperationsImpl.waitUntilReady(ServiceOperationsImpl.java:83)
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.ServiceOperationsImpl.waitUntilReady(ServiceOperationsImpl.java:37)
```

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #2672 

Use `waitUntilCondition(Objects::nonNull, amount, timeUnit)` instead of waitUntilReady for `Service` resource

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [X] I tested my code in Kubernetes
 - [X] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by manusa** [comment]
Given that [ServiceOperationsImpl](https://github.com/fabric8io/kubernetes-client/blob/1e1fdb81eabf92e6905f2d4e07c80e472d78bc75/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceOperationsImpl.java) extends [BaseOperation](https://github.com/fabric8io/kubernetes-client/blob/0c4513ff30ac9229426f1481a46fde2eb54933d9/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java) which in turns implements the [Resource](https://github.com/fabric8io/kubernetes-client/blob/0b84591916ec5ce6aaa98827cfe3658219d33b5d/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Resource.java) interface which extends the [Readiable](https://github.com/fabric8io/kubernetes-client/blob/0b84591916ec5ce6aaa98827cfe3658219d33b5d/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Readiable.java) and [VersionWatchAndWaitable](https://github.com/fabric8io/kubernetes-client/blob/0b84591916ec5ce6aaa98827cfe3658219d33b5d/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/VersionWatchAndWaitable.java) interfaces, the [Readiness#isReady ](https://github.com/fabric8io/kubernetes-client/blob/c65b4547d47d075c2d403e9a475d3d3f40b274b7/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L58) method, should **never** throw an Exception.

The fact is that from our current DSL point of view, we consider every Resource as waitable/readiable, so waitUntilReady() method is generated for all resources. This means that calling this method for any of the Resources that aren't currently handled in the Readiness#isReady method will throw an exception. 

https://github.com/fabric8io/kubernetes-client/blob/c65b4547d47d075c2d403e9a475d3d3f40b274b7/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L66-L85

https://github.com/fabric8io/kubernetes-client/blob/c65b4547d47d075c2d403e9a475d3d3f40b274b7/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L58-L64

The fix should be to replace line 62 by an existence check Objects:nonNull of a resource retrieved from the server, and **maybe** warn the user about the resource not being of what **we** consider of a "RediableKubernetesResource" type.

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java [hunk 1]
```diff
@@ -59,10 +65,30 @@ public static boolean isReady(HasMetadata item) {
...
+    List<String> readinessApplicableResources = new ArrayList<>();
+    readinessApplicableResources.add("Node");
+    readinessApplicableResources.add("Deployment");
+    readinessApplicableResources.add("ReplicaSet");
+    readinessApplicableResources.add("StatefulSet");
+    readinessApplicableResources.add("Pod");
+    readinessApplicableResources.add("ReplicationController");
+
+    return readinessApplicableResources;
+  }
```
Comment (manusa) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java:90]: If I'm not mistaken, you're basically constructing **the same** String for each method invocation.

Just create a static class variable `String READINESS_APPLICABLE_RESOURCES`

Comment (manusa) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java:90]: In understand that you're doing this because you extend it on the OpenShiftReadiness class, but approach should be the same.

Create a static String in each class, and then implement a **non-static** `String getReadinessApplicableResources()` that will return each of the applicable static strings. Obviously the OpenShiftReadiness method has an `@Override` annotation.
