### PR TITLE
fix: ensures kind is set for generic resource lists

### LINKED ISSUE #5729: Kind is `null` in for `GenericKubernetesResource` informer `ResourceEventHandler
### Describe the bug

When I create an informer that uses `GenericKubernetesResource` the kind of the existing resources is `null`, sample:

```java
var informer = client.genericKubernetesResources("v1","ConfigMap").inAnyNamespace().runnableInformer(0);
        informer.addEventHandler(new ResourceEventHandler<GenericKubernetesResource>() {
            @Override
            public void onAdd(GenericKubernetesResource configMap) {
                System.out.println("config map kind "+configMap.getKind());
            }

            @Override
            public void onUpdate(GenericKubernetesResource configMap, GenericKubernetesResource t1) {
            }

            @Override
            public void onDelete(GenericKubernetesResource configMap, boolean b) {
            }
        });
        informer.start();
```
It is already `null` in cache.
It is strange that, if I create a new `ConfigMap` with the client, it gets propagated properly.

### Fabric8 Kubernetes Client version

6.10.0

### Steps to reproduce

See sample above. Try it with minikube for example.

### Expected behavior

Kind field is propagated

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
No specific logs
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes #5729

There are two additional thoughts here:
1. we should not need to, but we could do this for types other than generic if we add setKind to HasMetadata.
2. the logic is currently only doing this for lists as other operations and events doen't seem to have the same problem - but we could of course move the logic into the updateApiVersion if needed.

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
> we should not need to, but we could do this for types other than generic if we add setKind to HasMetadata.

Shouldn't be necessary since the kind is hardcoded during model generation.

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/BaseClient.java [hunk 1]
```diff
@@ -116,7 +117,7 @@ public void onClose(Executor executor) {
 
   BaseClient(final HttpClient httpClient, Config config, ExecutorSupplier executorSupplier,
       KubernetesSerialization kubernetesSerialization) {
-    this.closable = Collections.newSetFromMap(new WeakHashMap<>());
+    this.closable = Collections.synchronizedSet(Collections.newSetFromMap(new WeakHashMap<>()));
```
Comment (manusa) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/BaseClient.java:120]: Do these changes have anything to do with this PR?

**Review by manusa — APPROVED** [review]
