### PR TITLE
Fixes Issue 2306: make Informers work with KubernetesServer CRUD mode

### LINKED ISSUE #2306: KubernetesServer CRUD mode and informers
I'd like to make informers work with the CRUD API. The current behavior seems to break with the reflector code within the informer. For example:

```
    @Test
    void testCrudInformer() throws InterruptedException {
        final KubernetesServer server = new KubernetesServer(true, true);
        server.before();

        KubernetesClient client = server.getClient();
        SharedInformerFactory factory = client.informers();
        SharedIndexInformer<Pod> podInformer = factory.sharedIndexInformerFor(Pod.class, PodList.class, 4000);
        podInformer.addEventHandler(
                new ResourceEventHandler<Pod>() {
                    @Override
                    public void onAdd(Pod obj) {
                    }

                    @Override
                    public void onUpdate(Pod oldObj, Pod newObj) {
                    }

                    @Override
                    public void onDelete(Pod oldObj, boolean deletedFinalStateUnknown) {
                    }
                });
        factory.startAllRegisteredInformers();
        Thread.sleep(5000);
        factory.stopAllRegisteredInformers();
    }
```

Leads to the following NPE in the reflector....

```
Jun 22, 2020 7:15:46 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[58658] starting to accept connections
19:15:46.956 [informer-controller-Pod] INFO  io.fabric8.kubernetes.client.informers.cache.Controller - informer#Controller: ready to run resync and reflector runnable
19:15:46.967 [informer-controller-Pod] INFO  io.fabric8.kubernetes.client.informers.cache.Reflector - Started ReflectorRunnable watch for class io.fabric8.kubernetes.api.model.Pod
Jun 22, 2020 7:15:47 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[58658] received request: GET /api/v1/namespaces/test/pods HTTP/1.1 and responded: HTTP/1.1 200 OK
19:15:47.397 [informer-controller-Pod] WARN  io.fabric8.kubernetes.client.informers.cache.Controller - Reflector list-watching job exiting because the thread-pool is shutting down
 java.util.concurrent.RejectedExecutionException: Error while starting ReflectorRunnable watch
	at io.fabric8.kubernetes.client.informers.cache.Reflector.listAndWatch(Reflector.java:85) ~[kubernetes-client-4.10.1.jar:?]
	at io.fabric8.kubernetes.client.informers.cache.Controller.run(Controller.java:112) ~[kubernetes-client-4.10.1.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.NullPointerException
	at io.fabric8.kubernetes.client.informers.cache.Reflector.reListAndSync(Reflector.java:95) ~[kubernetes-client-4.10.1.jar:?]
	at io.fabric8.kubernetes.client.informers.cache.Reflector.listAndWatch(Reflector.java:80) ~[kubernetes-client-4.10.1.jar:?]
	... 2 more
```

Which in turn happens because the list type (PodList) that the reflector gets back has a null metadata object:
```
  private void reListAndSync() {
    final L list = getList();
    final String latestResourceVersion = list.getMetadata().getResourceVersion(); // NPE: Metadata is null
    ...
```

### PR DESCRIPTION
**Pull request by lalithsuresh**
## Description

Fixes #2306: make Informers work with KubernetesServer CRUD mode

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by lalithsuresh** [comment]
Rebasing against master (e8c47dc3ce9ecfc1567c4ed7b2d90f15b4cae8b6) to avoid merge conflict in CHANGELOG.md

**Comment by lalithsuresh** [comment]
May I know why the license check is failing? The logs don't reveal why.

File: kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CrudInformerTest.java [hunk 1]
```diff
@@ -0,0 +1,72 @@
+/**
+ * Copyright (C) 2020 VMware, Inc.
```
Comment (rohanKanojia) [inline kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CrudInformerTest.java:2]: I think license check is failing due to this :-(

Comment (rohanKanojia) [reply kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CrudInformerTest.java:2]: Right now we have a fixed license header which includes Red Hat as the copyright owner. We faced similar issues when accepting contributions from an Oracle employee in #2030

Comment (lalithsuresh) [reply kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CrudInformerTest.java:2]: This is an unusual requirement. What's the fix?

Comment (rohanKanojia) [reply kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CrudInformerTest.java:2]: For now, Would it be possible for you to change owner to Red Hat? We do have plans to make license headers generic( #2045)

Comment (lalithsuresh) [reply kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CrudInformerTest.java:2]: Thanks. Would it be possible to just add this test case to an existing test class instead? Keeps things simple. :)

Comment (rohanKanojia) [reply kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CrudInformerTest.java:2]: We can do that, but I don't remember if we have any test class for testing informers in crud mode :roll_eyes: . Do you think it's a good idea moving it here: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java ?

**Comment by dev-gaur** [comment]
Not sure If I'm right here but if we're adding informers support to the crud mock server.. shouldn't we also update the resourceVersion of the resource when it's updated?

File: kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CrudInformerTest.java (hunk 1 above)
Comment (lalithsuresh) [reply kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CrudInformerTest.java]: Fixed.

**Review by manusa — APPROVED** [review]

**Comment by manusa** [comment]
[merge]
