### PR TITLE
set resourceVersion for before replacing RawCustomResource

### LINKED ISSUE #3023: custom resources: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I'm trying to use an "unstructured" client using custom resource as workaround and I have something like this:

```java
CustomResourceDefinitionContext ctx = ... ;
Map<String, Object> unstructured = ...;

return kubernetesClient
    .customResource(ctx)
    .inNamespace(namespace)
    .createOrReplace(unstructured);
```

Sometimes, I get an exception like:

```
Message: kamelets.camel.apache.org "aws-sqs-source-v1alpha1" is invalid: metadata.resourceVersion:
 Invalid value: 0x0: must be specified for an update. Received status: Status(apiVersion=v1, code=422,
 details=StatusDetails(causes=[StatusCause(field=metadata.resourceVersion, message=Invalid value: 0x0:
 must be specified for an update, reason=FieldValueInvalid, additionalProperties={})], 
group=camel.apache.org, kind=kamelets, name=aws-sqs-source-v1alpha1, retryAfterSeconds=null, uid=null, 
additionalProperties={}), kind=Status, message=kamelets.camel.apache.org "aws-sqs-source-v1alpha1" is 
invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update, 
metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, 
additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={})
```

### PR DESCRIPTION
**Pull request by matthyx**
## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

Fixes #3023

### CODE REVIEW

**Comment by matthyx** [comment]
@lburgazzoli can you try with this patch?

**Review by oscerd — APPROVED** [review]

**Comment by lburgazzoli** [comment]
@matthyx seems to work ! thx

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java [hunk 1]
```diff
@@ -893,11 +893,18 @@ public Watch watch(Map<String, String> labels, ListOptions options, Watcher<Stri
       }
 
       try {
+        String nameFromObject = (String) metadata.get("name");
         // re-add for edit call
         if (originalResourceVersion != null) {
           metadata.put(RESOURCE_VERSION, originalResourceVersion);
+        } else {
+          // we get resourceVersion from existing object
+          // possible race condition if object has been deleted since the HTTP_CONFLICT exception?
```
Comment (manusa) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java:902]: This implementation should match what we have in:

https://github.com/fabric8io/kubernetes-client/blob/b54d41f854d4a34ebf82cef8310f4226f702f834/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L65-L74

In that case there is no check for deletion since the [CreateOrReplaceHelper#createOrReplace](https://github.com/fabric8io/kubernetes-client/blob/02826311061aa15633f7482397ae3ce11e26d34e/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/CreateOrReplaceHelper.java#L48) retries the operation 3 times.

A quick mitigation for some of the cases could be to check if the `metadata.deletionTimestamp` is not blank.

Comment (matthyx) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java:902]: I think this refactoring should belong to a different issue/pr because the existing code cannot replace the RCR without a `resourceVersion`.
The goal of this comment was just to highlight the potential issue for later.

Comment (manusa) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java:902]: Don't worry, we can revisit this later.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Review by rohanKanojia — APPROVED** [review]
