### PR TITLE
fix #3561: ensuring closure of okhttp resources

### LINKED ISSUE #3561: OkHttp connection leak on retries within OperationSupport.retryWithExponentialBackoff
I received the following log messages in my current project, after enabling `kubernetes.request.retry.backoffLimit`. Before that, I saw 500 responses from the Kubernetes API while I was overloading it with requests.

```
A connection to *** was leaked. Did you forget to close a response body?

java.lang.Throwable: response.body().close()
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:149) ~[okhttp-3.14.9.jar:?]
	at okhttp3.internal.connection.Transmitter.callStart(Transmitter.java:116) ~[okhttp-3.14.9.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:78) ~[okhttp-3.14.9.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.retryWithExponentialBackoff(OperationSupport.java:591) ~[kubernetes-client-5.9.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:564) ~[kubernetes-client-5.9.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:527) ~[kubernetes-client-5.9.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleDelete(OperationSupport.java:295) ~[kubernetes-client-5.9.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:619) ~[kubernetes-client-5.9.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:535) ~[kubernetes-client-5.9.0.jar:?]
```

I tracked this down to the following code snippet in [OperationSupport.java](https://github.com/fabric8io/kubernetes-client/blob/51475cd8e5ce997211dda223ac9cb782205ce4be/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L586-L609). 

On retry, the previous response body isn't closed before the next retry starts. See code nippet below, with necessary additions marked with `NEW CODE START` and `NEW CODE END`.

I'd be happy to create a PR, at the same time I'm unsure how to write a unit test for this. Please advise how to write a unit test for this, or if you would be willing to accept a unit test without additional tests.

```
        if (numRetries < requestRetryBackoffLimit && response.code() >= 500) {
          retryInterval = retryIntervalCalculator.getInterval(numRetries);
          LOG.debug("HTTP operation on url: {} should be retried as the response code was {}, retrying after {} millis", request.url(), response.code(), retryInterval);
          // NEW CODE START
          if(response.body() != null) {
            response.body().close();
          }
          // NEW CODE END
        } else {
          return response;
        }
```

### PR DESCRIPTION
**Pull request by shawkins**
## Description
Addresses #3561 and other okhttp usage that is not closed.

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java [hunk 1]
```diff
@@ -592,6 +592,9 @@ protected Response retryWithExponentialBackoff(OkHttpClient client, Request requ
         if (numRetries < requestRetryBackoffLimit && response.code() >= 500) {
           retryInterval = retryIntervalCalculator.getInterval(numRetries);
           LOG.debug("HTTP operation on url: {} should be retried as the response code was {}, retrying after {} millis", request.url(), response.code(), retryInterval);
+          if (response.body() != null) {
+            response.body().close();
+          }
```
Comment (manusa) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java:597]: The response implements Closable, the OkHttp leak message refers to that closable method not getting invoked.

https://github.com/fabric8io/kubernetes-client/issues/3561#issuecomment-959685922

**Review by manusa — APPROVED** [review]
