### PR TITLE
fix (kubernetes-client-api) : Fix NO_PROXY check in HttpClientUtil (#4247)

### LINKED ISSUE #4247: Openshift Client ignores NO_PROXY setting
### Describe the bug

The ConfigBuilder ignores .withNoProxy() Setting. I must set the HttpProxy to null in order to connect to my PaaS.

### Fabric8 Kubernetes Client version

6.0.0-RC1

### Steps to reproduce

Does not work:

        Config config = new ConfigBuilder()
                .withNoProxy("*.my.domain.com") // does not work: Socket Exception: "read timed out"
                .build();

        try (final KubernetesClient client = new KubernetesClientBuilder().withConfig(config).build()) {

            System.out.println(Arrays.toString(config.getNoProxy()));
            System.out.println(client.getConfiguration().getCurrentContext().getName());
            System.out.println(config.getUsername());
            System.out.println(config.getOauthToken());

            client.pods().inNamespace("default").list().getItems().stream().map(pod -> pod.getMetadata().getName()).forEach(System.out::println);

Weird workaround that works:

        Config config = new ConfigBuilder()
                .withHttpProxy(null)
                .withHttpsProxy(null)
                .build();

        try (final KubernetesClient client = new KubernetesClientBuilder().withConfig(config).build()) {
            //client.authorization().v1().localSubjectAccessReview()

            System.out.println(Arrays.toString(config.getNoProxy()));
            System.out.println(client.getConfiguration().getCurrentContext().getName());
            System.out.println(config.getUsername());
            System.out.println(config.getOauthToken());

            client.pods().inNamespace("default").list().getItems().stream().map(pod -> pod.getMetadata().getName()).forEach(System.out::println);

### Expected behavior

        Config config = new ConfigBuilder()
                .withNoProxy("*.my.domain.com")
                .build();

This should work / not be ignored.

### Runtime

OpenShift

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Windows

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

Kubernetes API Server version:    v1.21.11+6b3cbdd

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fix #4247 

+ Modify NO_PROXY check to use `.endsWith` instead of `.contains` to
  better match host name.
+ Add a check to throw an Exception if any of NO_PROXY contains `*`

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

File: kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java [hunk 1]
```diff
@@ -225,4 +210,39 @@ public static void applyCommonConfiguration(Config config, HttpClient.Builder bu
...
+        }
+      }
+    }
+    return false;
+  }
+
+  private static boolean isValidNoProxy(String[] noProxy) throws MalformedURLException {
+    if (noProxy != null) {
+      for (String np : noProxy) {
+        if (np.indexOf('*') > -1) {
```
Comment (shawkins) [inline kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java:231]: Could this instead be a check for any invalid url character?  Someone could use other meta/invalid characters.

**Review by manusa — APPROVED** [review]
