### PR TITLE
Fixes flaky integration tests.

### LINKED ISSUE #1182: Explicit sleep on the thread can make tests flaky
I see there are tests which wait until the resource is destroyed by explicitly waiting 30s. This has two problems at least:

  * it doesn't guarantee that condition is met 
  * if it's met faster we waste time sitting idle and the whole build is slower for no reason

https://github.com/fabric8io/kubernetes-client/blob/7ea9ce885f9fad72949db6e3f5cc8dceb8ce8766/kubernetes-itests/src/test/java/io/fabric8/openshift/RouteIT.java#L106

If there is a way in the client to check if the resource does not exist we could think about using polling instead? For example by using this little library https://github.com/awaitility/awaitility/

### PR DESCRIPTION
**Pull request by dev-gaur**
Fixes #1182.

### CODE REVIEW

File: kubernetes-itests/src/test/java/io/fabric8/kubernetes/ConfigMapIT.java [hunk 1]
```diff
@@ -101,14 +114,26 @@ public void update() {
...
-    Thread.sleep(30000);
+    try {
+      if (client.configMaps().inNamespace(currentNamespace).list().getItems().size()!= 0) {
+        client.configMaps().inNamespace(currentNamespace).delete();
+      }
+
+      Delete<ConfigMap> configMapDelete = new Delete<ConfigMap>(ConfigMap.class, client, "configmap1", currentNamespace);
+      await().atMost(30, TimeUnit.SECONDS).until(configMapDelete);
+    } catch (NullPointerException exception) {
+      cleanup();
```
Comment (bartoszmajsak) [inline kubernetes-itests/src/test/java/io/fabric8/kubernetes/ConfigMapIT.java]: Isn't it a potentially endless recursion here? Why are we handling `NPE` here?

File: kubernetes-itests/src/test/java/io/fabric8/kubernetes/NetworkPolicyIT.java [hunk 2]
```diff
@@ -158,16 +165,25 @@ public void update(){
...
     assertEquals(0,networkPolicyList.getItems().size());
   }
 
   @After
   public void cleanup() throws InterruptedException {
-    client.network().networkPolicies().delete();
-    // wait for graceful deletion
-    Thread.sleep(6 * 1000);
+    try {
+      if (client.network().networkPolicies().list().getItems().size()!= 0) {
```
Comment (bartoszmajsak) [inline kubernetes-itests/src/test/java/io/fabric8/kubernetes/NetworkPolicyIT.java]: `client.network().networkPolicies()` can be a variable to start with. Then perhaps `!var.list().isEmpty()` might improve readability a bit?

File: kubernetes-itests/src/test/java/io/fabric8/kubernetes/NetworkPolicyIT.java [hunk 3]
```diff
@@ -158,16 +165,25 @@ public void update(){
...
+        client.network().networkPolicies().delete();
+      }
+      Delete<NetworkPolicy> networkPolicyDelete = new Delete<NetworkPolicy>(NetworkPolicy.class, client, "networkpolicy", currentNamespace);
+      await().atMost(30, TimeUnit.SECONDS).until(networkPolicyDelete);
+    }catch (NullPointerException exception) {
+      cleanup();
```
Comment (bartoszmajsak) [inline kubernetes-itests/src/test/java/io/fabric8/kubernetes/NetworkPolicyIT.java]: Formatting + the same question about an endless call as in the other test.

File: kubernetes-itests/src/test/java/io/fabric8/kubernetes/ServiceAccountIT.java [hunk 4]
```diff
@@ -85,23 +91,35 @@ public void list() {
...
-    // Wait for resources to get destroyed
-    Thread.sleep(30000);
+    try {
+      client.serviceAccounts().inNamespace(currentNamespace).delete();
+      // Wait for resources to get destroyed
+      Delete<ServiceAccount> serviceAccount1Delete = new Delete<ServiceAccount>(ServiceAccount.class, client, "serviceaccount1", currentNamespace);
+      Delete<ServiceAccount> serviceAccount2Delete = new Delete<ServiceAccount>(ServiceAccount.class, client, "serviceaccount2", currentNamespace);
+
+      await().atMost(30, TimeUnit.SECONDS).until(serviceAccount1Delete);
+      await().atMost(30, TimeUnit.SECONDS).until(serviceAccount2Delete);
```
Comment (bartoszmajsak) [inline kubernetes-itests/src/test/java/io/fabric8/kubernetes/ServiceAccountIT.java]: Can this be combined to one `&&` condition ?

File: kubernetes-itests/src/test/java/io/fabric8/commons/Delete.java [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+        return ((OpenShiftClient)this.client).buildConfigs().inNamespace(this.namespace).list().getItems().size() == 0;
+      case "ConfigMap":
+        return this.client.configMaps().inNamespace(this.namespace).list().getItems().size() == 0;
+      case "StatefulSet":
+        return this.client.apps().statefulSets().inNamespace(this.namespace).list().getItems().size() == 0;
+      case "Deployment":
+      return this.client.apps().deployments().inNamespace(this.namespace).list().getItems().size() == 0;
+      case "Service":
+        return this.client.services().inNamespace(this.namespace).list().getItems().size() == 0;
+      case "ServiceAccount":
```
Comment (rohanKanojia) [inline kubernetes-itests/src/test/java/io/fabric8/commons/Delete.java]: Why is service account name hardcoded here?

File: kubernetes-itests/src/test/java/io/fabric8/commons/Delete.java [hunk 6]
```diff
@@ -0,0 +1,57 @@
...
+
+  public Delete(Class<T> typeParameterClass, KubernetesClient client, String name, String namespace) {
+    this.typeParameterClass = typeParameterClass;
+    this.client = client;
+    this.name = name;
+    this.namespace = namespace;
+  }
+
+  @Override
+  public Boolean call() throws Exception {
```
Comment (rohanKanojia) [inline kubernetes-itests/src/test/java/io/fabric8/commons/Delete.java]: Are you sure that Exception is thrown from this method? if not, please remove this.

File: kubernetes-itests/src/test/java/io/fabric8/commons/Ready.java [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+  public Boolean call() throws Exception {
+    switch (this.typeParameterClass.getSimpleName()) {
+      case "Route":
+        return ((OpenShiftClient)this.client).routes().inNamespace(this.namespace).withName(this.name).get() != null;
+      case "Template":
+        return ((OpenShiftClient)this.client).templates().inNamespace(this.namespace).withName(this.name).get() != null;
+      case "ImageStream":
+        return ((OpenShiftClient)this.client).imageStreams().inNamespace(this.namespace).withName(this.name).get()!= null;
+      case "DeploymentConfig":
+        System.out.println("In deployment config ready");
```
Comment (rohanKanojia) [inline kubernetes-itests/src/test/java/io/fabric8/commons/Ready.java]: You might wanna remove this ;-)

File: kubernetes-itests/src/test/java/io/fabric8/kubernetes/ConfigMapIT.java [hunk 8]
```diff
@@ -16,7 +16,10 @@
 
 package io.fabric8.kubernetes;
 
+import io.fabric8.commons.Delete;
+import io.fabric8.commons.Ready;
 import io.fabric8.kubernetes.api.model.*;
+import io.fabric8.kubernetes.client.Config;
```
Comment (rohanKanojia) [inline kubernetes-itests/src/test/java/io/fabric8/kubernetes/ConfigMapIT.java]: Do we need this import?

File: kubernetes-itests/src/test/java/io/fabric8/kubernetes/ConfigMapIT.java [hunk 9]
```diff
@@ -89,10 +95,17 @@ public void list() {
 
   @Test
   public void update() {
+    Ready<ConfigMap> configMap1Ready = new Ready<ConfigMap>(ConfigMap.class, client, "configmap1", currentNamespace);
```
Comment (rohanKanojia) [inline kubernetes-itests/src/test/java/io/fabric8/kubernetes/ConfigMapIT.java]: Explicit type argument can be replaced with <>

File: kubernetes-itests/src/test/java/io/fabric8/commons/Ready.java (hunk 7 above)
Comment (dev-gaur) [reply kubernetes-itests/src/test/java/io/fabric8/commons/Ready.java]: oops

File: kubernetes-itests/src/test/java/io/fabric8/commons/Delete.java (hunk 6 above)
Comment (dev-gaur) [reply kubernetes-itests/src/test/java/io/fabric8/commons/Delete.java]: forgot to omit this

File: kubernetes-itests/src/test/java/io/fabric8/kubernetes/ConfigMapIT.java (hunk 9 above)
Comment (dev-gaur) [reply kubernetes-itests/src/test/java/io/fabric8/kubernetes/ConfigMapIT.java]: noted. thanks!

File: kubernetes-itests/src/test/java/io/fabric8/commons/Delete.java (hunk 5 above)
Comment (dev-gaur) [reply kubernetes-itests/src/test/java/io/fabric8/commons/Delete.java]: oops

File: kubernetes-itests/src/test/java/io/fabric8/kubernetes/ConfigMapIT.java (hunk 8 above)
Comment (dev-gaur) [reply kubernetes-itests/src/test/java/io/fabric8/kubernetes/ConfigMapIT.java]: forgot to omit

File: kubernetes-itests/src/test/java/io/fabric8/kubernetes/ConfigMapIT.java (hunk 1 above)
Comment (dev-gaur) [reply kubernetes-itests/src/test/java/io/fabric8/kubernetes/ConfigMapIT.java]: I followed this up from [here](https://github.com/fabric8io/kubernetes-client/pull/1121/files#diff-e892e898797ea5223e863136b7348d7cR134) .

If the 'entity/resource' is not responding yet, we can catch the exception and try cleaning up again. I think, practically, the recursive loop here being endless is unlikely. Therefore, I let it there as good measure.

@rohanKanojia what do you think?

File: kubernetes-itests/src/test/java/io/fabric8/kubernetes/ServiceAccountIT.java (hunk 4 above)
Comment (dev-gaur) [reply kubernetes-itests/src/test/java/io/fabric8/kubernetes/ServiceAccountIT.java]: As in this ?
```await().atMost(30, TimeUnit.SECONDS).until(serviceAccount1Delete && serviceAccount2Delete);```

This doesn't work. data types of serviceAccountDelete instances aren't compatible for this boolean specific operation.

File: kubernetes-itests/src/test/java/io/fabric8/kubernetes/ConfigMapIT.java (hunk 1 above)
Comment (rohanKanojia) [reply kubernetes-itests/src/test/java/io/fabric8/kubernetes/ConfigMapIT.java]: Even if ending up in a recursive loop is unlikely; I believe we should limit this to some finite number of retry attempts, rather than having no control over the number of retries encountered

File: kubernetes-itests/src/test/java/io/fabric8/kubernetes/NetworkPolicyIT.java (hunk 2 above)
Comment (dev-gaur) [reply kubernetes-itests/src/test/java/io/fabric8/kubernetes/NetworkPolicyIT.java]: Hey, 

Attempting this would look like [this](https://gist.github.com/rohanKanojia/f49dd6ce84b9317fb21f8653e92e8c81#file-networkpolicyit-java-L47) and i think this line looks really long and highly unreadable. I would be happy to take any suggestions from you on workarounds.

**Comment by rohanKanojia** [comment]
Please ignore this centos CI build, I'm currently working on fixing this.

**Comment by rohanKanojia** [comment]
retest this please

**Comment by rohanKanojia** [comment]
[merge]
