### PR TITLE
Fix NPE on initial requests while syncing

### LINKED ISSUE #2978: Multiple sharedInformer creation: NullPointerException while running
While migrating a project that uses many watchers for different object types to shared informers, I am facing the following error after informers get started:
```
2021-04-09 08:48:43 WARNING io.fabric8.kubernetes.client.informers.cache.Controller run Reflector list-watching job exiting because the thread-pool is shutting down
java.util.concurrent.RejectedExecutionException: Error while starting ReflectorRunnable watch
	at io.fabric8.kubernetes.client.informers.cache.Reflector.listAndWatch(Reflector.java:87)
	at io.fabric8.kubernetes.client.informers.cache.Controller.run(Controller.java:109)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
```
I tried to reuse the `sharedInformer` or have different ones, but in both cases, I see this exception happening around 60 times for a total of 120 created informers.

### PR DESCRIPTION
**Pull request by akram**
## Description

Fix #2978 
Adds null check on cache object metadata.
## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ReflectUtils.java [hunk 1]
```diff
@@ -39,6 +42,9 @@ public static ObjectMeta objectMetadata(Object obj) throws ReflectiveOperationEx
   }
 
   public static String namespace(Object obj) throws ReflectiveOperationException {
+    if( obj == null ) {
```
Comment (rohanKanojia) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ReflectUtils.java:45]: I noticed ReflectUtils.namespace() wasn't getting used anywhere. Do we need this null check?

**Comment by rohanKanojia** [comment]
I've added some tests in https://github.com/akram/kubernetes-client/pull/345 for this PR. Would appreciate if you could review and merge it.

**Review by rohanKanojia — APPROVED** [review]
Looks good, Thanks

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ReflectUtils.java (hunk 1 above)
Comment (akram) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ReflectUtils.java:45]: Findbugs is asking for that actually.

**Review by manusa — APPROVED** [review]
LGTM, thx
