### PR TITLE
Fix #2857: Fix the log of an unexpected error from an Informer's EventHandler

### LINKED ISSUE #2857: Incomplete error log in case of error in an EventHandler of an Informer
If for some reason, the user code in the EventHandler hooked into an Informer throws an exception, the resulting error logs are not informative. It logs as:
`ERROR io.fabric8.kubernetes.client.informers.cache.ProcessorListener - Failed invoking null event handler: {}`

The log format is inorrect, and it would be nice to have the stack trace.

### PR DESCRIPTION
**Pull request by hibnico**
## Description
This is simply fixing the format of the log, and it also log the exception itself to get an informative stacktrace

It fixes #2857 

## Type of change
 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by rohanKanojia — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorListener.java [hunk 1]
```diff
@@ -60,7 +60,7 @@ public void run() {
         Thread.currentThread().interrupt();
         return;
       } catch (Exception ex) {
-        log.error("Failed invoking {} event handler: {}", ex.getMessage());
+        log.error("Failed invoking {} event handler: {}", handler, ex.getMessage(), ex);
```
Comment (jorsol) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorListener.java:63]: Logger.error only takes the Throwable without format

https://javadoc.io/static/org.slf4j/slf4j-api/1.7.30/org/slf4j/Logger.html#error-java.lang.String-java.lang.Throwable-

Comment (hibnico) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorListener.java:63]: I cannot find a documentation of this behaviour, but if the last argument of a format is an exception, then the exception is properly propataged to the underlying logger, so the associated stack trace may be printed.
For instance, see https://github.com/qos-ch/slf4j/blob/master/slf4j-api/src/main/java/org/slf4j/helpers/MessageFormatter.java#L415

Comment (manusa) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorListener.java:63]: Do we want to log the stack trace though?

Comment (hibnico) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorListener.java:63]: I think we do. The exception is an error coming from user's code, the implementation of the event handler. As the implementer, I would like to know exactly where is the mistake I made. A simple message won't help me (don't blame me but some of my code still throws NPE from time to time 😅)

**Review by manusa — APPROVED** [review]
LGTM, thx!
