### PR TITLE
deps: Remove commons-codec dependency (trouble with GraalVM)

### LINKED ISSUE #3672: Native build fails because it considers optional `commons-codec` dependency
### Describe the bug

See https://github.com/quarkiverse/quarkus-operator-sdk/issues/175#issuecomment-999158762 for more details.

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

1. Clone https://github.com/quarkiverse/quarkus-operator-sdk 
2. mvn clean install
3. cd integration-tests
4. mvn verify -Dnative

### Expected behavior

Native build should work correctly.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.22.3@latest

### Environment

macOS

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by manusa**
## Description

Fix #3672

Alternative to #3673

Using [Robert Harder's Base64 class](http://iharder.sourceforge.net/current/java/base64/).
Extracted from [Keycloak's repo](https://github.com/keycloak/keycloak/blob/422ae0b3dbc1fb99f939860c78f5631fe2d83805/common/src/main/java/org/keycloak/common/util/Base64.java) since it was already trimmed off of unneeded methods.

/cc @geoand 

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java [hunk 1]
```diff
@@ -406,38 +407,33 @@ public InputStream read() {
...
-                  e.printStackTrace();
-                }
-              }
-            ).exec("sh", "-c", String.format("cat %s | base64", PodUpload.shellQuote(source)));
-            return new org.apache.commons.codec.binary.Base64InputStream(in) {
-              @Override
-              public void close() throws IOException {
-                watch.close();
-                super.close();
+    return new Callable<InputStream>() {
```
Comment (metacosm) [inline kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java:410]: I don't think that we need to wrap these calls anymore.

Comment (manusa) [reply kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java:410]: woops, changing that and adding changelog entry

File: pom.xml [hunk 2]
```diff
@@ -114,7 +114,6 @@
     <lombok.version>1.18.22</lombok.version>
     <snakeyaml.version>1.28</snakeyaml.version>
     <bouncycastle.version>1.70</bouncycastle.version>
-    <commons-codec.version>1.15</commons-codec.version>
     <commons-compress.version>1.21</commons-compress.version>
```
Comment (metacosm) [inline pom.xml:117]: We might need to add some exclusions because I think that other commons dependencies are pulling `commons-codec` as well, though I guess it shouldn't be an issue.

**Review by metacosm — COMMENTED** [review]
LGTM apart from some minor comments.

File: pom.xml (hunk 2 above)
Comment (manusa) [reply pom.xml:117]: Checking dependency tree

Comment (manusa) [reply pom.xml:117]: Dependency tree doesn't show any transitivity

**Comment by geoand** [comment]
Nice!

**Review by shawkins — APPROVED** [review]
LGTM, but ideally the printStackTraces would get converted to logs.

**Comment by manusa** [comment]
> LGTM, but ideally the printStackTraces would get converted to logs.

I must have missed some of those :sweat: 
On it.

**Review by metacosm — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]

**Comment by jorsol** [comment]
Can I ask why not use the Java Base64 class? https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html

**Comment by metacosm** [comment]
> Can I ask why not use the Java Base64 class? https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html

Because it doesn't work well for streaming data.
